### ISSUE TITLE
Stop using `shift` in `SourceNode.prototype.fromStringWithSourceMap`

### ISSUE THREAD

**Issue by fitzgen** [mozilla/source-map#111]
It is O(n) and its inside a loop for each mapping :( very sad. Instead we should just advance an index through the array of remaining lines.

Depends on #103 because that changes the `fromStringWithSourceMap` code, but we will still be using `shift`.

**Comment by fictitious** [comment]
Exactly:

![source-map-cpu-profile](https://cloud.githubusercontent.com/assets/189742/26484463/1e5e4fbc-41a7-11e7-84f3-e21b7d2a9fec.png)
