### ISSUE TITLE
Define how `util.relative` should work and test it thoroughly

### ISSUE THREAD

**Issue by lydell** [mozilla/source-map#128]
Just like for `util.join`, we should nail down how `util.relative` should work:
- URLs vs paths
- Edge cases, like the empty string
- Path normalization?

Then we should write tests:
- In test-util.js
- For all code that uses `util.relative`

This is important, so we don’t repeat edge-case bugs like #123.

**Comment by tromey** [comment]
I don't think there's anything left to do here.
