### ISSUE TITLE
Remove "Failed to find module: amdefine" spew when successfully running node Makefile.dryice.js

### ISSUE THREAD

**Issue by ejpbruel** [mozilla/source-map#140]
I've tried to build the source-map library from source, by following the README.md. When I run the following commands:

npm link
node Makefile.dryice.js

I get the following output:

Creating dist/SourceMap.jsm
Failed to find module: amdefine from source-map/source-map-consumer
Failed to find module: amdefine from source-map/util
Failed to find module: amdefine from source-map/binary-search
Failed to find module: amdefine from source-map/array-set
Failed to find module: amdefine from source-map/base64-vlq
Failed to find module: amdefine from source-map/base64
Failed to find module: amdefine from source-map/source-map-generator
Failed to find module: amdefine from source-map/source-node

Creating dist/test/Utils.jsm
Failed to find module: amdefine from test/source-map/util
Failed to find module: amdefine from lib/source-map/util

Creating dist/test/test_api.js

Creating dist/test/test_array_set.js

Creating dist/test/test_base64_vlq.js

Creating dist/test/test_base64.js

Creating dist/test/test_binary_search.js

Creating dist/test/test_dog_fooding.js

Creating dist/test/test_source_map_consumer.js

Creating dist/test/test_source_map_generator.js

Creating dist/test/test_source_node.js

Creating dist/test/test_util.js

Creating dist/source-map.js
Failed to find module: amdefine from source-map/source-map-generator
Failed to find module: amdefine from source-map/base64-vlq
Failed to find module: amdefine from source-map/base64
Failed to find module: amdefine from source-map/util
Failed to find module: amdefine from source-map/array-set
Failed to find module: amdefine from source-map/source-map-consumer
Failed to find module: amdefine from source-map/binary-search
Failed to find module: amdefine from source-map/source-node

Creating dist/source-map.min.js

I've made sure the amdefine module is installed by running npm -g install amdefine, and that NODE_PATH is set appropriately.

When I create an minimal index.js that simply does require('amdefine'), the module is found without a hitch. Either I'm doing something wrong, or there is something wrong with the build script.

**Comment by niemyjski** [comment]
+1

**Comment by jkrems** [comment]
Closing because the package no longer heavily depends on AMD.
