### ISSUE TITLE
Is there a way to get the class corresponding to the mapping generated output ? 

### ISSUE THREAD

**Issue by tallandroid** [mozilla/source-map#143]
My requirement is to tweak the corresponding class attribute mapping to the line and column number which i got as an output of allGeneratedPositionsFor API. Wanted to confirm if there is any existing implementation ? 
I am willing to contribute, but wanted to check before hand.

**Comment by jkrems** [comment]
I'll err on the side of closing this issue since there hasn't been any activity in the past few years.
