### ISSUE TITLE
Optimize generator with respect to sorting mappings

### ISSUE THREAD

**Issue by crisptrutski** [mozilla/source-map#149]
This is along the same vein as https://github.com/mozilla/source-map/issues/148, but less drastic and specialized. 

See that there have already been thoughts in this direction here: https://github.com/mozilla/source-map/blob/master/lib/source-map/source-map-generator.js#L297-L299

1. Small gains from keeping mappings always-sorted as an invariant
2. Especially cheap insertion of mappings when added in-order

Implementation wise this could be implemented by using a custom data type for `_mappings`. 

Some sort of heap, or even a plain array with sorted insertion and using `push` for mappings beyond maximum seen (line, column).

**Comment by crisptrutski** [comment]
OK so I took a stab at this, and found that:

1. Heap was too slow in sorted and unsorted input cases.
2. Insertion sort with bisection, and fast path for sorted input was too slow in the unsorted input case - about twice as expensive as current behaviour. Damn `.splice`. Tried some tricks, like chunking mappings to keep splice's cheap, and writing a bespoke random-access-insert method, but complexity grew fast and didn't reliably beat `.sort`-at-end performance.
3. Deoptimizing version is by far the simplest, gives large wins on sorted input and similar to existing performance on unsorted input.

So (3) is a clear winner here, I'll provide the benchmarking script and result summary in a bit once I've cleaned it up.

One thing is that I've only tested against v8 (Node) and using quite a few NPM dependencies. How would you suggest gathering the spidermonkey results? Bundle the scripts up and run with Narwhal or Firefox?

Actually would prefer to skip the other VM if you don't mind - my cheeky rationale is that the performance shift is simple to reason about:

  Replace O(n log n) sort with O(n) sanity check in best case, but pay both costs in worst case. And extra cost is negligible in worst case (OK I guess numbers would help here - but c'mon the sanity check is cheap :))

**Comment by fitzgen** [comment]
> How would you suggest gathering the spidermonkey results?

In the future, I would recommend just using Firefox.
