### ISSUE TITLE
Sourcemap doesnt give any output if the sass variables are used as expressions

### ISSUE THREAD

**Issue by tallandroid** [mozilla/source-map#153]
We were trying to consume the API allGeneratedSourcesFor for getting the mappings. Interestingly for the sass variables directly getting consumed , we could get the generated positions. However, for any variables getting used as expressions we are not able to get the mapping. Is this by design or intentional ?

**Comment by prashanthseshadri** [comment]
+1
Yeah, even i tried it out. For property like:
$padding-1: 10;
$padding-2: 20;
body {
    padding: $padding-1 $padding-2; //This does not work
    padding: $padding-1 //This works and gives the mapping in allGeneratedSourcesFor API
}
Is this intended? I am wondering how will things in developer tools in such case help in debugging?

**Comment by fitzgen** [comment]
Can you provide a test case, steps-to-reproduce, your expected outcome, and the actual outcome?

cc @ejpbruel

**Comment by prashanthseshadri** [comment]
Test case:
pages/_home.scss:
$padding: 10px;
.my-padding-selector {
      padding: $padding $padding;
      padding-left: $padding;
  }

compiled css:
.my-padding-selector {
  padding: 10px 10px;
  padding-left: 10px; }

Called:
smc.allGeneratedPositionsFor({
        source: 'pages/_home.scss',
        line: 1
    })

Output:
[ { line: 3,
    column: 16,
    lastColumn: null },
  { line: 3,
    column: 20,
    lastColumn: null } ]

Expected:
[ { line: 3,
    column: 16,
    lastColumn: null },
  { line: 3,
    column: 20,
    lastColumn: null }, 
  { line: 3,
    column: 11,
    lastColumn: null },
  { line: 3,
    column: 15,
    lastColumn: null }, 
  { line: 3,
    column: 17,
    lastColumn: null },
  { line: 3,
    column: 21,
    lastColumn: null } ]

I might be wrong in column number indexing (due to diff. interpretation of space when copied from my editor). 

Let me know if you need more details!

**Comment by fitzgen** [comment]
Can you include the generated source map? We can only report data that is
encoded in the source map, and this feels like a funky source map.

Try uploading the map + the source files to this tool:
https://sokra.github.io/source-map-visualization/

**Comment by prashanthseshadri** [comment]
https://sokra.github.io/source-map-visualization/#base64,Lm15LXBhZGRpbmcgewogIHBhZGRpbmctcmlnaHQ6IDEwcHg7CiAgcGFkZGluZzogMTBweCAxMHB4OyB9CgovKiMgc291cmNlTWFwcGluZ1VSTD1teUZpbGUuY3NzLm1hcCAqLwo=,eyJ2ZXJzaW9uIjozLCJtYXBwaW5ncyI6IkFBQ0MsV0FBWTtFQUNULGFBQWEsRUFGTixJQUFJO0VBR1gsT0FBTyxFQUFFLFNBQWlCIiwic291cmNlcyI6WyJteUZpbGUuc2NzcyJdLCJuYW1lcyI6W10sImZpbGUiOiJteUZpbGUuY3NzIn0=,ICRwYWRkaW5nOiAxMHB4OwogLm15LXBhZGRpbmcgewogICAgcGFkZGluZy1yaWdodDogJHBhZGRpbmc7CiAgICBwYWRkaW5nOiAkcGFkZGluZyAkcGFkZGluZzsKIH0K

**Comment by prashanthseshadri** [comment]
Another example (which covers the above example + usage of mathematical expression - which is also not been detected)

https://sokra.github.io/source-map-visualization/#base64,Lm15LXBhZGRpbmcgewogIHBhZGRpbmctcmlnaHQ6IDEwcHg7CiAgcGFkZGluZzogMTBweCAxMHB4OwogIHBhZGRpbmctbGVmdDogMjBweDsgfQoKLyojIHNvdXJjZU1hcHBpbmdVUkw9bXlGaWxlLmNzcy5tYXAgKi8K,eyJ2ZXJzaW9uIjozLCJtYXBwaW5ncyI6IkFBQ0MsV0FBWTtFQUNULGFBQWEsRUFGTixJQUFJO0VBR1gsT0FBTyxFQUFFLFNBQWlCO0VBQzFCLFlBQVksRUFBRSxJQUFVIiwic291cmNlcyI6WyJteUZpbGUuc2NzcyJdLCJuYW1lcyI6W10sImZpbGUiOiJteUZpbGUuY3NzIn0=,ICRwYWRkaW5nOiAxMHB4OwogLm15LXBhZGRpbmcgewogICAgcGFkZGluZy1yaWdodDogJHBhZGRpbmc7CiAgICBwYWRkaW5nOiAkcGFkZGluZyAkcGFkZGluZzsKICAgIHBhZGRpbmctbGVmdDogMiokcGFkZGluZzsKIH0K

**Comment by fitzgen** [comment]
I think that `allGeneratedPositionsFor` is doing the right thing here (ignoring off by one's in your original post, which you attribute to your editor?)

There are only two mappings that have an original line == 1, and they are getting returned in the results.

**Comment by fitzgen** [comment]
The same applies to the second example. The source map doesn't contain any other mappings, if you want more fine grained infor, then the scss compiler will need to encode that in the source maps it generates.

**Comment by prashanthseshadri** [comment]
Okay. Thanks for the information. So as per you if the sourcemap contains the right encoding information, the code should be able to pick it up? And may i know how to generate that granular information? Currently i am using sass with --sourcemap option.

**Comment by prashanthseshadri** [comment]
Basically i would want to identify even the usage of concatenation of vars. and expression using the line and col. no. identifers. for the line. no-1 variable.

**Comment by fitzgen** [comment]
You will likely need to patch the scss compiler to emit multiple mappings for the same generated location: the "10px" in the generated code could be considered to come from the location of the use of "$padding" AND/OR the definition of "$padding". If the scss compiler wants to encode both in the source map, it should add two mappings for that generated locations: one for each of those original locations.

**Comment by prashanthseshadri** [comment]
Okay, i guess i can take this up with the sass compiler folks and ask if thats intended. Thanks once again!
