### ISSUE TITLE
Please add CommonJS-compatible browser build to package.json

### ISSUE THREAD

**Issue by appden** [mozilla/source-map#158]
Using browserify ends up requiring the `amddefine` module and its dependencies into the build. It would be great if you'd publish the browser build onto npm and add it to the `browser` field in the `package.json` file (see https://github.com/substack/browserify-handbook#browser-field). Thanks!

**Comment by fitzgen** [comment]
Would merge a PR that added this.

**Comment by niemyjski** [comment]
+1

**Comment by niemyjski** [comment]
The normal build should just output commonjs and wrap that in a umd wrapper (https://github.com/umdjs/umd) this will make it work eveywhere (node, browser etc).

I have an example of this here: https://github.com/exceptionless/Exceptionless.JavaScript/blob/master/dist/exceptionless.es5.js#L1613-L1627

Then you just return the exports and it works everywhere :).

**Comment by jkrems** [comment]
The library is now distributed as a "normal" npm package.
