### ISSUE TITLE
Support the "sections" alternate source map structure

### ISSUE THREAD

**Issue by fitzgen** [mozilla/source-map#16]
https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit?pli=1#heading=h.535es3xeprgt

**Comment by jlfwong** [comment]
A subset of this now works in https://github.com/mozilla/source-map/issues/127 :)

**Comment by amasad** [comment]
@jlfwong what does #127 leave unimplemented from this?

**Comment by zanona** [comment]
Wow, it would be really awesome to have this so we could have source maps for HTML files with inline scripts on different parts of a document, especially web components. Can I please just confirm if the spec proposes this but it has not been used or implemented yet?
Thanks guys

**Comment by tromey** [comment]
> Wow, it would be really awesome to have this so we could have source maps for HTML files with inline scripts on different parts of a document, especially web components. Can I please just confirm if the spec proposes this but it has not been used or implemented yet?
Inline `<script>` can set the source map URL (and the `sourceURL` if desired).  This can work fine without needing the sections approach.  However, there are still some bugs in this area in Firefox at least.  I'm not totally sure this answers your question...?

**Comment by tromey** [comment]
>  I actually meant when you have multiple <script> tags in a single HTML file since only one sourceMappingURL declaration is accepted per file.

I think the intent is that each separate `<script>` can have its own `sourceMappingURL`; but like I mentioned, there are some bugs in the Firefox devtools in this area.  I don't think source-mapping the entire HTML document is supported (if it is, that must be some browser's own extension).

>  I wondered if the section feature was actually implemented or just a proposal.

I think it is implemented; however, in this library, there's no support for a sectioned source map where the sections are not inlined.  Nobody ever implemented the proposed fetching API.

**Comment by jkrems** [comment]
The basic feature (support for indexed source maps) has been implemented in its most commonly used form (embedded `map`, not external `url` reference). I created https://github.com/mozilla/source-map/issues/437 to track support for external URLs.
