### ISSUE TITLE
SourceMapConsumer shouldn't allocate an object for each parsed mapping

### ISSUE THREAD

**Issue by fitzgen** [mozilla/source-map#161]
cc @ejpbruel @jlongster 

Instead, it should decode each mapping into an array buffer that serves as an array of the following struct:

``` C++
struct Mapping {
  // The number of segments that appeared in this mapping. Only the following
  // `numberOfSegments` fields have valid data. Should be 2, 5, or 6 for well formed
  // mappings.
  uint32_t numberOfSegments;

  int32_t generatedLine;
  int32_t generatedColumn;
  int32_t sourceIndex;
  int32_t originalLine;
  int32_t originalColumn;
  int32_t nameIndex;
}
```

Then, `SourceMapConsumer.prototype.__generatedMappings` and `SourceMapConsumer.prototype.__originalMappings` would hold indices into this array buffer, rather than object references.

**Comment by jkrems** [comment]
I'll throw this into the same bucket as #187 and #189 (which means: close this for now). This info may still proof valuable but would have to be mapped to the current state of the library.
