### ISSUE TITLE
SourceNode.fromStringWithSourceMap throws when there are more mapping lines than generated code lines

### ISSUE THREAD

**Issue by matthewp** [mozilla/source-map#174]
This was reported in https://github.com/mozilla/source-map/issues/138 but fixed by a bug in another project. I think it is still a valid source-map bug as [stated here](https://github.com/mozilla/source-map/issues/138#issuecomment-62853402).

The scenario I have is:

1. Source map is created from escodegen.
2. Source map and code from 1 is ran through uglify which generates a new source map.
3. Calling SourceNode.fromStringWithSourceMap with the code/map from 2 will throw.

The reason it throws is that uglify calls `addMapping` [here](https://github.com/mishoo/UglifyJS2/blob/master/lib/sourcemap.js#L80) but the existing mappings remain from the original transformation.

fromStringWithSourceMap expects there to be fewer generatedLines than lines in the generated code.

I'd be happy to submit a patch for this but could use some guidance on what needs to be done to fix this.

**Comment by matthewp** [comment]
I think we can just ignore the mappings in this case. The generatedLines no longer exist and have been replaced, essentially. They do not need to be part of the new map you'll create with SourceNode.  

Does this sound correct @fitzgen?  If so I'll submit a PR that fixes the issue.

**Comment by fitzgen** [comment]
I don't fully understand the issue (a minimal test case would help me understand, and would be something we can add to the test suite along with the bug fix) but that sounds like it makes sense to me.

If @sokra says the bug is in `fromStringWithSourceMap`, then I believe it, as he originally wrote that method.

**Comment by matthewp** [comment]
@fitzgen I would feel better if you did understand the issue so let me explain again.

If you start with source file with 10 lines and create a source map for that.

Then you take the code and map and reduce the code down to 1 line and add new mappings to the source map by calling `generator.addMapping`.

The existing mappings are still there (there is not a way to remove mappings I believe, correct?)

When you then call `fromStringWithSourceMap` it expects the generated code lines (now 1) to **less than** any mappings `generatedLine` number.

I'm a bit of a sourcemap newbie so please correct me if I'm getting something wrong here @fitzgen or @sokra.  It makes sense to me that we can simply discard the mappings that refer to, for example, line 10 which is no longer part of the generated code.

Here's a higher level question, the spec is set up so that you can have "dead code" mappings, correct? That is mappings that refer to generated lines/columns that are no longer part of the generated code.

**Comment by matthewp** [comment]
Also I'll see about creating a test case.

**Comment by fitzgen** [comment]
See comment here: https://github.com/bitovi/source-map/commit/377291d28456eb77ed8dc1dbd432330ab7165053#commitcomment-10565532

This is a bug in code using the source-map library, not a bug in the library itself.

**Comment by matthewp** [comment]
@fitzgen thank you for taking the time to do such a detailed answered.  Here's my reply:

> Keep running the transformation on the string directly, but as you go keep track of line and column offset adjustments made by your transformation, and apply the offset adjustments to the mappings as you go. This approach requires a lot of careful bookkeeping and seems pretty easy to mess up.

Is it possible to modify existing mappings? What uglify does now is to add new mappings as it makes its transformations. So the pre-existing mappings are still there, and as you say they are now invalid.  This seems to work fine if uglify is the end-of-the-line but in my case I need to then concat the mangled files.

So my recommendation to them them should be, I think, to use the existing map to get the original position but apply the mappings to a new SourceMapGenerator. So the mappings that refer back to the original positions are there, but the intermediate mappings are now gone.

Maybe ideally they should be using SourceNode#walk but that is probably a larger change than I can expect from them.

Thanks again for your brain! :)

**Comment by fitzgen** [comment]
> So my recommendation to them them should be, I think, to use the existing map to get the original position but apply the mappings to a new SourceMapGenerator. So the mappings that refer back to the original positions are there, but the intermediate mappings are now gone.

Yup &mdash; it doesn't make sense to mutate the existing source map because you are semantically creating a new source map for a new generated source. You have outlined the correct approach.

**Comment by matthewp** [comment]
Thanks.
