### ISSUE TITLE
SourceMapGenerator should use deflated mappings too

### ISSUE THREAD

**Issue by fitzgen** [mozilla/source-map#195]
Like `SourceMapConsumer` does.

This will likely be a nice perf boost for serializing source maps.

Additionally, it will let us unify `compareByGeneratedPosition{Inflated,Deflated}` again.

**Comment by fitzgen** [comment]
One more goodie this would bring: SourceMapConsumer.fromSourceMap wouldn't need to copy mappings anymore because it wouldn't need to mutate them.

**Comment by jkrems** [comment]
The deflated variants have been removed in https://github.com/mozilla/source-map/commit/1e521ff50f90901e651c7ef106d3ba168e4423fb, so I'll go ahead and close this issue.
