### ISSUE TITLE
Include dist in package.json files

### ISSUE THREAD

**Issue by andy-hanson** [mozilla/source-map#212]
I'm working on a [library](https://github.com/mason-lang/esast) that requires source-map. I want this library to work both in node.js and in the browser. This means I want the same code to work with npm and with bower.

For npm, the package.json includes this code:

	"files": [
		"source-map.js",
		"lib/"
	]

So when I run `npm install mozilla/source-map`, I get `lib` but not `dist`.

For bower, I can't use `lib` because that uses CommonJS-style modules and I want to use AMD. So I have to use `dist`.

The problem would be solved if `dist` were included in the package.json `files` so that I could use the same import statement (to `source-map/dist/source-map.min.js`) on the web and in node.

**Comment by TrySound** [comment]
:-1: If you use npm you can use browserify. You can generate and sourcemaps and umd.

**Comment by TrySound** [comment]
@fitzgen source-map module uses in many modules with different versions. If every version will have the same size whole npm ecosystem will be broken in some day. Do you remember Wirth's law? It's true with the size too.
