### ISSUE TITLE
Using source map with browserify

### ISSUE THREAD

**Issue by elfet** [mozilla/source-map#214]
Hi!

It is possible to use this source maps with browserify? 

How to write transform for browserify which will be support source maps?

**Comment by TrySound** [comment]
@elfet Man, read documentation please: `debug` option.
https://github.com/substack/node-browserify#browserifyfiles--opts

**Comment by elfet** [comment]
man, i read docs.

**Comment by fitzgen** [comment]
Let's try and keep the snark to a minimum.

Unfortunately, I don't know browserify internals. Probably better to ask them.
