### ISSUE TITLE
Attention, size!

### ISSUE THREAD

**Issue by TrySound** [mozilla/source-map#215]
Hey, @fitzgen ! Size of module is too big. Now dist/test are not ignored.

**Comment by TrySound** [comment]
https://github.com/mozilla/source-map/issues/212

**Comment by fitzgen** [comment]
Fixed in ef7006f8d1647e0a83fdc60f04f5a7ca54886f86

**Comment by TrySound** [comment]
@fitzgen And you really think that sourcemaps in NPM module is good idea? Any code can be minified and built with sourcemaps. This module still too big. Let's reopen this to discuss.

**Comment by Siilwyn** [comment]
@fitzgen any thoughts on @TrySound's comment?

The package size seems rather big because of the un-minified files.

**Comment by jsantell** [comment]
Agreed -- large dependencies in npm is a huge detriment, and anyone using npm as their package manager will encounter atleast one other common JS/node/browserify-style package and have to deal with it, and if it's something someone wants to just drop in a page or use any other means, then the dist directory is still there. npm has won, and using npm as the package manager to consume npm-style modules (commonJS) is the default -- consumers must expect to handle or transform these modules, like #212.

**Comment by TrySound** [comment]
I think you should leave or minified version with external sourcemap or debug version with inline sourcemap. I don't think there is a need for both.
