### ISSUE TITLE
Async/await debugging jumping

### ISSUE THREAD

**Issue by amcdnl** [mozilla/source-map#221]
I'm having spotty debugging experiences when I try to debug code with async/await using `transform-async-to-generator` babel plugin ( although I've tried almost every other combination ).

Essentially code with a await will skip to the end of the method and then go into the compiled code. [video](http://www.screencast.com/t/qQW11FC8)

```
	export class Cat {
		async meow(){
			let p = await this.bat(); // <<<< this line runs
	        this.fart(); // <<<< then skips this line
			return p;  // <<<< and goes to this line ( always last line in fn )
		}
	}
```

If you take a look at the generated code for that function:

```
	meow() {
		var _this = this;

		return _asyncToGenerator(function* () {
			let p = yield _this.bat();
			_this.fart();
			return p;
		})();
	}
```

its no wonder regarding the results but source maps should handle this, right?

I've tried this with a variety of setups ( require hook / babel-node / babel cli / gulp babel ) and get same issue.  I'm using: Node 5.4.0 and Babel 6.4.0

I've created a demo project on [github](https://github.com/amcdnl/debug-hell). I've also posted the question on the [babel thread](http://discuss.babeljs.io/t/async-await-debugging-issues/132).

**Comment by jlongster** [comment]
Can you try in Firefox and see if it results in the same behavior?

Most likely, this is faulty source-map generation and not the fault of the lib itself. The compiler needs to give this lib correct information for it to work right.

**Comment by amcdnl** [comment]
I'm running in Node... I see it in Node-Inspector, VSCode Debugger and Webstorm Debugger. I'll try to replicate in browser though.

**Comment by fitzgen** [comment]
This issue would really benefit from a reduced test case and a link to https://sokra.github.io/source-map-visualization/ with the reduced test case's source map loaded.

**Comment by marjan-georgiev** [comment]
Here's an example:

```javascript
export class MyClass {

  async foo() {
    console.log('1. calling bar');
    let result = await this.bar();
    console.log('4. promise resolved');
    console.log('5.', result);
    return result;
  }

  async bar(){
    console.log('2. returning promise');

    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve('hello')
      }, 1000);
    });
  }
}

let ob = new MyClass();
ob.foo();
console.log('3. continuing execution...')
```

Here is the the sourcemap visualization for it [LINK](https://sokra.github.io/source-map-visualization/#base64,J3VzZSBzdHJpY3QnOwoKT2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsICJfX2VzTW9kdWxlIiwgewogIHZhbHVlOiB0cnVlCn0pOwoKZnVuY3Rpb24gX2FzeW5jVG9HZW5lcmF0b3IoZm4pIHsgcmV0dXJuIGZ1bmN0aW9uICgpIHsgdmFyIGdlbiA9IGZuLmFwcGx5KHRoaXMsIGFyZ3VtZW50cyk7IHJldHVybiBuZXcgUHJvbWlzZShmdW5jdGlvbiAocmVzb2x2ZSwgcmVqZWN0KSB7IGZ1bmN0aW9uIHN0ZXAoa2V5LCBhcmcpIHsgdHJ5IHsgdmFyIGluZm8gPSBnZW5ba2V5XShhcmcpOyB2YXIgdmFsdWUgPSBpbmZvLnZhbHVlOyB9IGNhdGNoIChlcnJvcikgeyByZWplY3QoZXJyb3IpOyByZXR1cm47IH0gaWYgKGluZm8uZG9uZSkgeyByZXNvbHZlKHZhbHVlKTsgfSBlbHNlIHsgUHJvbWlzZS5yZXNvbHZlKHZhbHVlKS50aGVuKGZ1bmN0aW9uICh2YWx1ZSkgeyBzdGVwKCJuZXh0IiwgdmFsdWUpOyB9LCBmdW5jdGlvbiAoZXJyKSB7IHN0ZXAoInRocm93IiwgZXJyKTsgfSk7IH0gfSBzdGVwKCJuZXh0Iik7IH0pOyB9OyB9CgpsZXQgTXlDbGFzcyA9IGV4cG9ydHMuTXlDbGFzcyA9IGNsYXNzIE15Q2xhc3MgewoKICBmb28oKSB7CiAgICB2YXIgX3RoaXMgPSB0aGlzOwoKICAgIHJldHVybiBfYXN5bmNUb0dlbmVyYXRvcihmdW5jdGlvbiogKCkgewogICAgICBjb25zb2xlLmxvZygnMS4gY2FsbGluZyBiYXInKTsKICAgICAgbGV0IHJlc3VsdCA9IHlpZWxkIF90aGlzLmJhcigpOwogICAgICBjb25zb2xlLmxvZygnNC4gcHJvbWlzZSByZXNvbHZlZCcpOwogICAgICBjb25zb2xlLmxvZygnNS4nLCByZXN1bHQpOwogICAgICByZXR1cm4gcmVzdWx0OwogICAgfSkoKTsKICB9CgogIGJhcigpIHsKICAgIHJldHVybiBfYXN5bmNUb0dlbmVyYXRvcihmdW5jdGlvbiogKCkgewogICAgICBjb25zb2xlLmxvZygnMi4gcmV0dXJuaW5nIHByb21pc2UnKTsKCiAgICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7CiAgICAgICAgc2V0VGltZW91dCgoKSA9PiB7CiAgICAgICAgICByZXNvbHZlKCdoZWxsbycpOwogICAgICAgIH0sIDEwMDApOwogICAgICB9KTsKICAgIH0pKCk7CiAgfQp9OwoKbGV0IG9iID0gbmV3IE15Q2xhc3MoKTsKb2IuZm9vKCk7CmNvbnNvbGUubG9nKCczLiBjb250aW51aW5nIGV4ZWN1dGlvbi4uLicpOwovLyMgc291cmNlTWFwcGluZ1VSTD1kYXRhOmFwcGxpY2F0aW9uL2pzb247YmFzZTY0LGV5SjJaWEp6YVc5dUlqb3pMQ0p6YjNWeVkyVnpJanBiSW1SbGJXOHZaR1Z0Ynk1cWN5SmRMQ0p1WVcxbGN5STZXMTBzSW0xaGNIQnBibWR6SWpvaU96czdPenM3T3p0SlFVRmhMRTlCUVU4c1YwRkJVQ3hQUVVGUExFZEJRV0lzVFVGQlRTeFBRVUZQTEVOQlFVTTdPMEZCUlc1Q0xFRkJRVTBzUzBGQlJ5eEhRVUZIT3pzN08wRkJRMVlzWVVGQlR5eERRVUZETEVkQlFVY3NRMEZCUXl4blFrRkJaMElzUTBGQlF5eERRVUZETzBGQlF6bENMRlZCUVVrc1RVRkJUU3hIUVVGSExFMUJRVTBzVFVGQlN5eEhRVUZITEVWQlFVVXNRMEZCUXp0QlFVTTVRaXhoUVVGUExFTkJRVU1zUjBGQlJ5eERRVUZETEhGQ1FVRnhRaXhEUVVGRExFTkJRVU03UVVGRGJrTXNZVUZCVHl4RFFVRkRMRWRCUVVjc1EwRkJReXhKUVVGSkxFVkJRVVVzVFVGQlRTeERRVUZETEVOQlFVTTdRVUZETVVJc1lVRkJUeXhOUVVGTkxFTkJRVU03TzBkQlEyWTdPMEZCUlVRc1FVRkJUU3hMUVVGSExFZEJRVVU3TzBGQlExUXNZVUZCVHl4RFFVRkRMRWRCUVVjc1EwRkJReXh6UWtGQmMwSXNRMEZCUXl4RFFVRkRPenRCUVVWd1F5eGhRVUZQTEVsQlFVa3NUMEZCVHl4RFFVRkRMRU5CUVVNc1QwRkJUeXhGUVVGRkxFMUJRVTBzUzBGQlN6dEJRVU4wUXl4clFrRkJWU3hEUVVGRExFMUJRVTA3UVVGRFppeHBRa0ZCVHl4RFFVRkRMRTlCUVU4c1EwRkJReXhEUVVGQk8xTkJRMnBDTEVWQlFVVXNTVUZCU1N4RFFVRkRMRU5CUVVNN1QwRkRWaXhEUVVGRExFTkJRVU03TzBkQlEwbzdRMEZEUmpzN1FVRkZSQ3hKUVVGSkxFVkJRVVVzUjBGQlJ5eEpRVUZKTEU5QlFVOHNSVUZCUlN4RFFVRkRPMEZCUTNaQ0xFVkJRVVVzUTBGQlF5eEhRVUZITEVWQlFVVXNRMEZCUXp0QlFVTlVMRTlCUVU4c1EwRkJReXhIUVVGSExFTkJRVU1zTkVKQlFUUkNMRU5CUVVNc1EwRkJRU0lzSW1acGJHVWlPaUprWlcxdkwyUmxiVzh1YW5NaUxDSnpiM1Z5WTJWU2IyOTBJam9pTGk0dkxpNHZjM0pqSW4wPQo=,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImRlbW8vZGVtby5qcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztJQUFhLE9BQU8sV0FBUCxPQUFPLEdBQWIsTUFBTSxPQUFPLENBQUM7O0FBRW5CLEFBQU0sS0FBRyxHQUFHOzs7O0FBQ1YsYUFBTyxDQUFDLEdBQUcsQ0FBQyxnQkFBZ0IsQ0FBQyxDQUFDO0FBQzlCLFVBQUksTUFBTSxHQUFHLE1BQU0sTUFBSyxHQUFHLEVBQUUsQ0FBQztBQUM5QixhQUFPLENBQUMsR0FBRyxDQUFDLHFCQUFxQixDQUFDLENBQUM7QUFDbkMsYUFBTyxDQUFDLEdBQUcsQ0FBQyxJQUFJLEVBQUUsTUFBTSxDQUFDLENBQUM7QUFDMUIsYUFBTyxNQUFNLENBQUM7O0dBQ2Y7O0FBRUQsQUFBTSxLQUFHLEdBQUU7O0FBQ1QsYUFBTyxDQUFDLEdBQUcsQ0FBQyxzQkFBc0IsQ0FBQyxDQUFDOztBQUVwQyxhQUFPLElBQUksT0FBTyxDQUFDLENBQUMsT0FBTyxFQUFFLE1BQU0sS0FBSztBQUN0QyxrQkFBVSxDQUFDLE1BQU07QUFDZixpQkFBTyxDQUFDLE9BQU8sQ0FBQyxDQUFBO1NBQ2pCLEVBQUUsSUFBSSxDQUFDLENBQUM7T0FDVixDQUFDLENBQUM7O0dBQ0o7Q0FDRjs7QUFFRCxJQUFJLEVBQUUsR0FBRyxJQUFJLE9BQU8sRUFBRSxDQUFDO0FBQ3ZCLEVBQUUsQ0FBQyxHQUFHLEVBQUUsQ0FBQztBQUNULE9BQU8sQ0FBQyxHQUFHLENBQUMsNEJBQTRCLENBQUMsQ0FBQSIsImZpbGUiOiJkZW1vL2RlbW8uanMiLCJzb3VyY2VSb290IjoiLi4vLi4vc3JjIn0=,ZXhwb3J0IGNsYXNzIE15Q2xhc3MgewoKICBhc3luYyBmb28oKSB7CiAgICBjb25zb2xlLmxvZygnMS4gY2FsbGluZyBiYXInKTsKICAgIGxldCByZXN1bHQgPSBhd2FpdCB0aGlzLmJhcigpOwogICAgY29uc29sZS5sb2coJzQuIHByb21pc2UgcmVzb2x2ZWQnKTsKICAgIGNvbnNvbGUubG9nKCc1LicsIHJlc3VsdCk7CiAgICByZXR1cm4gcmVzdWx0OwogIH0KCiAgYXN5bmMgYmFyKCl7CiAgICBjb25zb2xlLmxvZygnMi4gcmV0dXJuaW5nIHByb21pc2UnKTsKCiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4gewogICAgICBzZXRUaW1lb3V0KCgpID0+IHsKICAgICAgICByZXNvbHZlKCdoZWxsbycpCiAgICAgIH0sIDEwMDApOwogICAgfSk7CiAgfQp9CgpsZXQgb2IgPSBuZXcgTXlDbGFzcygpOwpvYi5mb28oKTsKY29uc29sZS5sb2coJzMuIGNvbnRpbnVpbmcgZXhlY3V0aW9uLi4uJykK)

**Comment by fitzgen** [comment]
Your link isn't working for me, but I tried myself on that test case and it [looks alright in the visualizer](https://sokra.github.io/source-map-visualization/#base64,ZnVuY3Rpb24gX2FzeW5jVG9HZW5lcmF0b3IoZm4pIHsgcmV0dXJuIGZ1bmN0aW9uICgpIHsgdmFyIGdlbiA9IGZuLmFwcGx5KHRoaXMsIGFyZ3VtZW50cyk7IHJldHVybiBuZXcgUHJvbWlzZShmdW5jdGlvbiAocmVzb2x2ZSwgcmVqZWN0KSB7IGZ1bmN0aW9uIHN0ZXAoa2V5LCBhcmcpIHsgdHJ5IHsgdmFyIGluZm8gPSBnZW5ba2V5XShhcmcpOyB2YXIgdmFsdWUgPSBpbmZvLnZhbHVlOyB9IGNhdGNoIChlcnJvcikgeyByZWplY3QoZXJyb3IpOyByZXR1cm47IH0gaWYgKGluZm8uZG9uZSkgeyByZXNvbHZlKHZhbHVlKTsgfSBlbHNlIHsgUHJvbWlzZS5yZXNvbHZlKHZhbHVlKS50aGVuKGZ1bmN0aW9uICh2YWx1ZSkgeyBzdGVwKCJuZXh0IiwgdmFsdWUpOyB9LCBmdW5jdGlvbiAoZXJyKSB7IHN0ZXAoInRocm93IiwgZXJyKTsgfSk7IH0gfSBzdGVwKCJuZXh0Iik7IH0pOyB9OyB9CgpleHBvcnQgY2xhc3MgTXlDbGFzcyB7CgogIGZvbygpIHsKICAgIHZhciBfdGhpcyA9IHRoaXM7CgogICAgcmV0dXJuIF9hc3luY1RvR2VuZXJhdG9yKGZ1bmN0aW9uKiAoKSB7CiAgICAgIGNvbnNvbGUubG9nKCcxLiBjYWxsaW5nIGJhcicpOwogICAgICBsZXQgcmVzdWx0ID0geWllbGQgX3RoaXMuYmFyKCk7CiAgICAgIGNvbnNvbGUubG9nKCc0LiBwcm9taXNlIHJlc29sdmVkJyk7CiAgICAgIGNvbnNvbGUubG9nKCc1LicsIHJlc3VsdCk7CiAgICAgIHJldHVybiByZXN1bHQ7CiAgICB9KSgpOwogIH0KCiAgYmFyKCkgewogICAgcmV0dXJuIF9hc3luY1RvR2VuZXJhdG9yKGZ1bmN0aW9uKiAoKSB7CiAgICAgIGNvbnNvbGUubG9nKCcyLiByZXR1cm5pbmcgcHJvbWlzZScpOwoKICAgICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHsKICAgICAgICBzZXRUaW1lb3V0KCgpID0+IHsKICAgICAgICAgIHJlc29sdmUoJ2hlbGxvJyk7CiAgICAgICAgfSwgMTAwMCk7CiAgICAgIH0pOwogICAgfSkoKTsKICB9Cn0KCmxldCBvYiA9IG5ldyBNeUNsYXNzKCk7Cm9iLmZvbygpOwpjb25zb2xlLmxvZygnMy4gY29udGludWluZyBleGVjdXRpb24uLi4nKTsKCi8vIyBzb3VyY2VNYXBwaW5nVVJMPWRhdGE6YXBwbGljYXRpb24vanNvbjtiYXNlNjQsZXlKMlpYSnphVzl1SWpvekxDSnpiM1Z5WTJWeklqcGJJbTE1TFdOc1lYTnpMbXB6SWwwc0ltNWhiV1Z6SWpwYlhTd2liV0Z3Y0dsdVozTWlPaUk3TzBGQlFVRXNUMEZCVHl4TlFVRk5MRTlCUVU4c1EwRkJRenM3UVVGRmJrSXNRVUZCVFN4TFFVRkhMRWRCUVVjN096czdRVUZEVml4aFFVRlBMRU5CUVVNc1IwRkJSeXhEUVVGRExHZENRVUZuUWl4RFFVRkRMRU5CUVVNN1FVRkRPVUlzVlVGQlNTeE5RVUZOTEVkQlFVY3NUVUZCVFN4TlFVRkxMRWRCUVVjc1JVRkJSU3hEUVVGRE8wRkJRemxDTEdGQlFVOHNRMEZCUXl4SFFVRkhMRU5CUVVNc2NVSkJRWEZDTEVOQlFVTXNRMEZCUXp0QlFVTnVReXhoUVVGUExFTkJRVU1zUjBGQlJ5eERRVUZETEVsQlFVa3NSVUZCUlN4TlFVRk5MRU5CUVVNc1EwRkJRenRCUVVNeFFpeGhRVUZQTEUxQlFVMHNRMEZCUXpzN1IwRkRaanM3UVVGRlJDeEJRVUZOTEV0QlFVY3NSMEZCUlRzN1FVRkRWQ3hoUVVGUExFTkJRVU1zUjBGQlJ5eERRVUZETEhOQ1FVRnpRaXhEUVVGRExFTkJRVU03TzBGQlJYQkRMR0ZCUVU4c1NVRkJTU3hQUVVGUExFTkJRVU1zUTBGQlF5eFBRVUZQTEVWQlFVVXNUVUZCVFN4TFFVRkxPMEZCUTNSRExHdENRVUZWTEVOQlFVTXNUVUZCVFR0QlFVTm1MR2xDUVVGUExFTkJRVU1zVDBGQlR5eERRVUZETEVOQlFVRTdVMEZEYWtJc1JVRkJSU3hKUVVGSkxFTkJRVU1zUTBGQlF6dFBRVU5XTEVOQlFVTXNRMEZCUXpzN1IwRkRTanREUVVOR096dEJRVVZFTEVsQlFVa3NSVUZCUlN4SFFVRkhMRWxCUVVrc1QwRkJUeXhGUVVGRkxFTkJRVU03UVVGRGRrSXNSVUZCUlN4RFFVRkRMRWRCUVVjc1JVRkJSU3hEUVVGRE8wRkJRMVFzVDBGQlR5eERRVUZETEVkQlFVY3NRMEZCUXl3MFFrRkJORUlzUTBGQlF5eERRVUZCSWl3aVptbHNaU0k2SW0xNUxXTnNZWE56TG1KMWFXeDBMbXB6SWl3aWMyOTFjbU5sYzBOdmJuUmxiblFpT2xzaVpYaHdiM0owSUdOc1lYTnpJRTE1UTJ4aGMzTWdlMXh1WEc0Z0lHRnplVzVqSUdadmJ5Z3BJSHRjYmlBZ0lDQmpiMjV6YjJ4bExteHZaeWduTVM0Z1kyRnNiR2x1WnlCaVlYSW5LVHRjYmlBZ0lDQnNaWFFnY21WemRXeDBJRDBnWVhkaGFYUWdkR2hwY3k1aVlYSW9LVHRjYmlBZ0lDQmpiMjV6YjJ4bExteHZaeWduTkM0Z2NISnZiV2x6WlNCeVpYTnZiSFpsWkNjcE8xeHVJQ0FnSUdOdmJuTnZiR1V1Ykc5bktDYzFMaWNzSUhKbGMzVnNkQ2s3WEc0Z0lDQWdjbVYwZFhKdUlISmxjM1ZzZER0Y2JpQWdmVnh1WEc0Z0lHRnplVzVqSUdKaGNpZ3BlMXh1SUNBZ0lHTnZibk52YkdVdWJHOW5LQ2N5TGlCeVpYUjFjbTVwYm1jZ2NISnZiV2x6WlNjcE8xeHVYRzRnSUNBZ2NtVjBkWEp1SUc1bGR5QlFjbTl0YVhObEtDaHlaWE52YkhabExDQnlaV3BsWTNRcElEMCtJSHRjYmlBZ0lDQWdJSE5sZEZScGJXVnZkWFFvS0NrZ1BUNGdlMXh1SUNBZ0lDQWdJQ0J5WlhOdmJIWmxLQ2RvWld4c2J5Y3BYRzRnSUNBZ0lDQjlMQ0F4TURBd0tUdGNiaUFnSUNCOUtUdGNiaUFnZlZ4dWZWeHVYRzVzWlhRZ2IySWdQU0J1WlhjZ1RYbERiR0Z6Y3lncE8xeHViMkl1Wm05dktDazdYRzVqYjI1emIyeGxMbXh2Wnlnbk15NGdZMjl1ZEdsdWRXbHVaeUJsZUdWamRYUnBiMjR1TGk0bktWeHVJbDE5,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm15LWNsYXNzLmpzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7O0FBQUEsT0FBTyxNQUFNLE9BQU8sQ0FBQzs7QUFFbkIsQUFBTSxLQUFHLEdBQUc7Ozs7QUFDVixhQUFPLENBQUMsR0FBRyxDQUFDLGdCQUFnQixDQUFDLENBQUM7QUFDOUIsVUFBSSxNQUFNLEdBQUcsTUFBTSxNQUFLLEdBQUcsRUFBRSxDQUFDO0FBQzlCLGFBQU8sQ0FBQyxHQUFHLENBQUMscUJBQXFCLENBQUMsQ0FBQztBQUNuQyxhQUFPLENBQUMsR0FBRyxDQUFDLElBQUksRUFBRSxNQUFNLENBQUMsQ0FBQztBQUMxQixhQUFPLE1BQU0sQ0FBQzs7R0FDZjs7QUFFRCxBQUFNLEtBQUcsR0FBRTs7QUFDVCxhQUFPLENBQUMsR0FBRyxDQUFDLHNCQUFzQixDQUFDLENBQUM7O0FBRXBDLGFBQU8sSUFBSSxPQUFPLENBQUMsQ0FBQyxPQUFPLEVBQUUsTUFBTSxLQUFLO0FBQ3RDLGtCQUFVLENBQUMsTUFBTTtBQUNmLGlCQUFPLENBQUMsT0FBTyxDQUFDLENBQUE7U0FDakIsRUFBRSxJQUFJLENBQUMsQ0FBQztPQUNWLENBQUMsQ0FBQzs7R0FDSjtDQUNGOztBQUVELElBQUksRUFBRSxHQUFHLElBQUksT0FBTyxFQUFFLENBQUM7QUFDdkIsRUFBRSxDQUFDLEdBQUcsRUFBRSxDQUFDO0FBQ1QsT0FBTyxDQUFDLEdBQUcsQ0FBQyw0QkFBNEIsQ0FBQyxDQUFBIiwiZmlsZSI6Im15LWNsYXNzLmJ1aWx0LmpzIiwic291cmNlc0NvbnRlbnQiOlsiZXhwb3J0IGNsYXNzIE15Q2xhc3Mge1xuXG4gIGFzeW5jIGZvbygpIHtcbiAgICBjb25zb2xlLmxvZygnMS4gY2FsbGluZyBiYXInKTtcbiAgICBsZXQgcmVzdWx0ID0gYXdhaXQgdGhpcy5iYXIoKTtcbiAgICBjb25zb2xlLmxvZygnNC4gcHJvbWlzZSByZXNvbHZlZCcpO1xuICAgIGNvbnNvbGUubG9nKCc1LicsIHJlc3VsdCk7XG4gICAgcmV0dXJuIHJlc3VsdDtcbiAgfVxuXG4gIGFzeW5jIGJhcigpe1xuICAgIGNvbnNvbGUubG9nKCcyLiByZXR1cm5pbmcgcHJvbWlzZScpO1xuXG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgICAgICByZXNvbHZlKCdoZWxsbycpXG4gICAgICB9LCAxMDAwKTtcbiAgICB9KTtcbiAgfVxufVxuXG5sZXQgb2IgPSBuZXcgTXlDbGFzcygpO1xub2IuZm9vKCk7XG5jb25zb2xlLmxvZygnMy4gY29udGludWluZyBleGVjdXRpb24uLi4nKVxuIl19,ZXhwb3J0IGNsYXNzIE15Q2xhc3MgewoKICBhc3luYyBmb28oKSB7CiAgICBjb25zb2xlLmxvZygnMS4gY2FsbGluZyBiYXInKTsKICAgIGxldCByZXN1bHQgPSBhd2FpdCB0aGlzLmJhcigpOwogICAgY29uc29sZS5sb2coJzQuIHByb21pc2UgcmVzb2x2ZWQnKTsKICAgIGNvbnNvbGUubG9nKCc1LicsIHJlc3VsdCk7CiAgICByZXR1cm4gcmVzdWx0OwogIH0KCiAgYXN5bmMgYmFyKCl7CiAgICBjb25zb2xlLmxvZygnMi4gcmV0dXJuaW5nIHByb21pc2UnKTsKCiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4gewogICAgICBzZXRUaW1lb3V0KCgpID0+IHsKICAgICAgICByZXNvbHZlKCdoZWxsbycpCiAgICAgIH0sIDEwMDApOwogICAgfSk7CiAgfQp9CgpsZXQgb2IgPSBuZXcgTXlDbGFzcygpOwpvYi5mb28oKTsKY29uc29sZS5sb2coJzMuIGNvbnRpbnVpbmcgZXhlY3V0aW9uLi4uJykK)

Looking in some more...

**Comment by fitzgen** [comment]
The test case won't compile for me with `babel-plugin-transform-regenerator`.

**Comment by marjan-georgiev** [comment]
That's pretty much the same sourcemap output I'm getting. Try debugging and setting a breakpoint on the line with the away call.
If you go to the next line from there, it will skip to the last line of the `foo` function.

What I would expect instead is to either
- stay and wait while the promise resolves and go to the line after the breakpoint, or
- go directly to the last line of the file, after the call of `of.foo()`, as that's what happens when await is hit.

**Comment by fitzgen** [comment]
Setting a breakpoint on which line?

**Comment by marjan-georgiev** [comment]
`let result = await this.bar();`

**Comment by fitzgen** [comment]
This is largely working as I expect in Firefox's debugger. Nor is this an issue with the `source-map` library. 

>  If you go to the next line from there, it will skip to the last line of the foo function.

That's because you are exiting that frame when you yield (or await). Any other JS could run in between and it might throw exceptions or hit other breakpoints, etc.

> stay and wait while the promise resolves and go to the line after the breakpoint

The debugger could choose to set a temporary breakpoint for when control returns to the generator/async function, so you can "step over" asynchronous things. I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1238745 for that behavior in Firefox. But again, this is not a bug with the `source-map` library.

**Comment by amcdnl** [comment]
@fitzgen Thanks for the feedback! Wasn't sure where it should land, i side with the temporary breakpoint!

**Comment by dmikov** [comment]
I understand that await releases the frame, so is await in .net releases thread. But it doesn't jump the hell away from it. As far as control flow of function under debugger goes it's linear, it really is NOT on the bottom skipping previous statements. The way it currently looks.
In reality while something could happen, nothing else happens on other threads.

**Comment by talarari** [comment]
hey, any update on this?
source maps are incorrect so debugging doesn't work well, see 
https://github.com/Microsoft/vscode/issues/19973
