### ISSUE TITLE
originalPositionFor always return null

### ISSUE THREAD

**Issue by seasonhuang** [mozilla/source-map#222]
I checkout the code from npm. And I found the originalPositionFor API always return null no matter what the parameters are.

I found the problem maybe from [this](https://github.com/mozilla/source-map/blob/master/lib/source-map-consumer.js#L615) . The types of variable at both side of "===" is different.

**Comment by lydell** [comment]
Perhaps you're passing the line and column numbers as strings, not as numbers? #109 #101

**Comment by seasonhuang** [comment]
Oh, yes, you are right. I passing the line and column from process.argv

**Comment by tromey** [comment]
I'm closing this one because it is a dup.
