### ISSUE TITLE
JSON.parse in SourceMapConsumer fails if the string provided isn't parsable

### ISSUE THREAD

**Issue by captainbrosset** [mozilla/source-map#225]
This is related to this Firefox DevTools bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1249888

STR:
- open Firefox dev edition
- open http://uni-wuerzburg.de/scripts/
- open the inspector
- open the browser console
- select a few nodes in the inspector until you see exceptions appear in the console

The interesting part of the exceptions is:

```
Full Message: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Full Stack: SourceMapConsumer@resource://gre/modules/commonjs/toolkit/loader.js ->  resource://devtools/shared/sourcemap/source-map.js:1281:20
```

source-map is used in Firefox DevTools to, among several things, consume CSS source maps so that the inspector can show original source links in the css rules view.
The SouceMapConsumer is used from:

https://dxr.mozilla.org/mozilla-central/source/devtools/server/actors/stylesheets.js#753

Turns out that on this website, the source map request comes back as text/html (a 404 error) and that causes source-map to fail when trying to JSON.parse it.

Over in the bugzilla bug we're going to make sure that the consumer isn't even called in these cases, but it might be good to try/catch the JSON.parse part nevertheless.

**Comment by fitzgen** [comment]
What would you expect the library to do in this case? Throw its own error instead?

**Comment by captainbrosset** [comment]
You're right, consumers of SourceMapConsumer need to be able to implement their own exception handling, so simply try/catching isn't enough.
I do think it would make sense for SourceMapConsumer to throw a developer-friendly error, which would be helpful when investigating issues. Maybe:
```
try {
  sourceMap = JSON.parse(aSourceMap.replace(/^\)\]\}'/, ''));
} catch (e) {
  throw new Error("The content of the source-map could not be parsed");
}
```

Might be a bit easier to understand than `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`.

**Comment by tromey** [comment]
I ended up documenting the JSON error, among others, on the MDN page.  So I'm inclined to just close this bug.
