### ISSUE TITLE
Questions about the source-map lib

### ISSUE THREAD

**Issue by dahart** [mozilla/source-map#226]
Hey guys, is this the right place to ask questions about source-map without having a specific issue or bug report? I'll repost somewhere else, or email directly, or split this post into several, if this is the wrong forum for this or I've used an inconvenient format.

I'm trying to setup a script to decode my production js call stacks. Ideally it would be a simple command line tool to read a source map and some text, and replace the minified call stack entries with decoded entries. My code is split into multiple modules, so my source map has multiple entries in it. I'm keeping the source maps on the back end, but not exposing them to the live site or the public -- I see a lot of client side solutions, but I'm looking for a back-end tool here.

My first question is whether you guys know of something that depends on source-map, or any other project, that does what I'm after. I can see a lot of people online asking for this, and quite a few paid services that offer this kind of functionality, so I'm surprised that I'm having a hard time finding anything that already handles it.

Second question - I've started writing the script I want, but the "original position" that comes out of SourceMapConsumer.originalPositionFor() is giving me the source and name properties of symbol at the exact location specified, and often it's a variable reference. I suppose this is the expected result, but in some cases, I'm get the line and column number for the variable declaration, rather than the location where the code was executing when it failed. What I would like is to find the name of the function being executed, since I want to decode a call stack. Is there a way I can get to the nearest enclosing function? I am looking at the API calls, but it's not clear I can get information on the enclosing frame of a position?

Perhaps there's a way to use the minified function symbol printed in the call stack instead of the generated position information? Is it possible to use the source-map API to translate the symbols instead of the positions?

For example, my production call stack might have lines that look like:

at Ye.e.Je (https://mysite.com/module_min.js:68:144)

I'm currently using "module_min.js:68:144" to find the original position, but perhaps I can use the "Ye.e.Je" minified function names instead?

Last question, or maybe just a suggestion. When source maps have multiple modules in them, they aren't JSON anymore. I'm using the Closure Compiler to generate my source maps. I've noticed some people asking about JSON.parse() failing on a source map file, as well as a lot of examples that qualify that they're not intended for source maps files with multiple maps.

I don't know the best way to parse a multi-map .map file, but I wrote a function for myself that reads the .map file, and creates a new SourceMapConsumer for each map in the file, then returns an object of all the consumers indexed by the 'file' property. I'm parsing my .map file in a probably super brain dead and inefficient way, so interested to see a better reference. But generally reading a map file with multiple maps seems like something that might be appropriate to have as part of source-map, or maybe at least a handy reference example somewhere.

**Comment by tromey** [comment]
> My first question is whether you guys know of something that depends on source-map, or any other project, that does what I'm after

I'm not aware of one.  Browsers should do it, but at least in Firefox we haven't implementing source-mapping for stack traces yet.

> Is there a way I can get to the nearest enclosing function?

No, I don't think so, because that's not encoded in the source map.  You could do it by using one of the JS parsers, though.

> Is it possible to use the source-map API to translate the symbols instead of the positions?

No.

> When source maps have multiple modules in them, they aren't JSON anymore.

Sorry, I don't understand this one.  The source map spec specifies two ways that a source map can be made, and they are both JSON.

**Comment by tromey** [comment]
I'm going to close this as non-actionable.
