### ISSUE TITLE
Assert that all entries added to `names` are strings when consuming a source map

### ISSUE THREAD

**Issue by wesleycho** [mozilla/source-map#230]
With the latest 0.5.4 release, I ran into a problem with grunt-contrib-concat where one of the keys iterated over in the source map being consumed (of jQuery in my instance) turns out to be the number `1223` (as logged at https://github.com/mozilla/source-map/blob/master/lib/source-map-consumer.js#L292), which errors out in https://github.com/mozilla/source-map/blob/master/lib/util.js#L271 because a number does not have have the `charCodeAt` method.

**Comment by fitzgen** [comment]
The `names` property of a source map is a list of strings, so what you describe is an invalid source map.

**Comment by fitzgen** [comment]
I suppose we can eagerly detect and throw in this case, instead of waiting for it to get deeper into internals...

**Comment by ashaffer** [comment]
PR #232 addresses this so that it behaves as it used to.

**Comment by fitzgen** [comment]
Fixed in https://github.com/mozilla/source-map/commit/b9de0424a6d701f9b10af8c3d8fc0e36d3483344
