### ISSUE TITLE
Possible regression introduced in 0.5.4 release (on Node 0.10)

### ISSUE THREAD

**Issue by redonkulus** [mozilla/source-map#231]
We are using webpack 1.x which uses uglify-js under the hood to compile our web application. uglify-js uses the source-map library to generate its source maps. However, it looks like the with the release of version 0.5.4, this caused a regression in Node 0.10 (for some reason not in 0.12). 

Specifically the line in webpack that throws an error:
https://github.com/webpack/webpack/blob/master/lib/optimize/UglifyJsPlugin.js#L66

```
ERROR in main.901a1d3558e2d907db4b.min.js from UglifyJs
TypeError: Cannot read property '1' of null
```

Perhaps the 0.5.4 release changed how the line numbers are returned. 

Is it possible to unpublish this release and re-release it under 0.6.0 to remove the regression?

I'm working on regression test for you to see. But this blocks our CI pipeline currently. Thanks!

**Comment by redonkulus** [comment]
@fitzgen

**Comment by redonkulus** [comment]
When I lock down source-map to 0.5.3 under webpack, the build works correctly. When I pull down this repository locally, running node 0.10 and run the tests, the tests do pass. But maybe that is because this issue isn't covered in the tests, I'm not sure yet.

**Comment by redonkulus** [comment]
Pulling in @ashaffer as well since part of the release was their PR.

**Comment by redonkulus** [comment]
Dependency list:

```
└─┬ webpack@1.13.0
  ├─┬ memory-fs@0.3.0
  │ └─┬ readable-stream@2.1.0
  │   └─┬ unreachable-branch-transform@0.5.1
  │     └─┬ recast@0.11.5
  │       └── source-map@0.5.4
  ├─┬ uglify-js@2.6.2
  │ └── source-map@0.5.4
  ├─┬ watchpack@0.2.9
  │ └─┬ chokidar@1.4.3
  │   └─┬ readdirp@2.0.0
  │     └─┬ readable-stream@2.1.0
  │       └─┬ unreachable-branch-transform@0.5.1
  │         └─┬ recast@0.11.5
  │           └── source-map@0.5.4
  └─┬ webpack-core@0.6.8
    └── source-map@0.4.4
```

**Comment by ashaffer** [comment]
Oh no. Please let me know if you can create a failing test case. I was pretty sure the changes I made shouldn't change it's behavior at all, but its certainly possible there's a weird case I hadn't considered.

**Comment by ashaffer** [comment]
Would you mind pasting the contents of the `warning` string passed into the erroring function? Assuming that it is a regression in source-map, that string should be different between 0.5.3 and 0.5.4

**Comment by ashaffer** [comment]
I also notice you seem to have two different and minor-version-incompatible version of source-map installed? webpack-core, which is presumably what's generating most of your source maps is using 0.4.4

**Comment by redonkulus** [comment]
@ashaffer thanks for responding! Here is the `warning` string:

```
Couldn't figure out mapping for common.b63a59506e45b5b15c72.min.js:40627,3 → 31,13280 [8]
Couldn't figure out mapping for 2.b63a59506e45b5b15c72.js:3,6 → 1,18 [62]
Couldn't figure out mapping for 3.b63a59506e45b5b15c72.js:3,6 → 1,18 [102]
Couldn't figure out mapping for 4.b63a59506e45b5b15c72.js:3,6 → 1,18 [106]
Couldn't figure out mapping for 5.b63a59506e45b5b15c72.js:3,6 → 1,18 [198]
Couldn't figure out mapping for main.901a1d3558e2d907db4b.min.js:11,6 → 1,54 [51]
Couldn't figure out mapping for Greeting.2fd1380212fa71fc3645.min.js:11,6 → 1,56 [62]
Couldn't figure out mapping for Depend.1c270af806746dccc164.min.js:11,6 → 1,56 [102]
Couldn't figure out mapping for Nest.46505f02500ad22d00dc.min.js:11,6 → 1,57 [106]
Couldn't figure out mapping for Shared.8000ce6d80d010003354.min.js:11,6 → 1,57 [198]
```

**Comment by redonkulus** [comment]
> I also notice you seem to have two different and minor-version-incompatible version of source-map installed? webpack-core, which is presumably what's generating most of your source maps is using 0.4.4

ya thats just what webpack comes with, webpack-core hasn't been updated in 6 months...

**Comment by ashaffer** [comment]
Hmm....it seems like there's more than one issue happening here. That warning message just plainly doesn't match that regex, and the changes I made shouldn't have altered the contents or presentation of such a message at all...so my guess is that Uglify's parser is expecting some older format of these warnings.

So best guess is that this warning simply wasn't being triggered at all before. If you run this against source-map 0.5.3, does it even get into this function (and if so what is the warning string)? 

Also, if you go into webpack-core and manually update source-map to the same version does it work?

**Comment by ashaffer** [comment]
So, if my theory is correct, you should be seeing an exception thrown here that wasn't happening before:

https://github.com/mishoo/UglifyJS2/blob/45ddb9caeb200615b9f0ced0ed83fa95f0c51b23/lib/output.js#L311

Can you provide the `token.file`, `current_line`, `token.line`, etc values for that exception?

**Comment by redonkulus** [comment]
> So best guess is that this warning simply wasn't being triggered at all before. If you run this against source-map 0.5.3, does it even get into this function (and if so what is the warning string)?

on 0.5.3, it never gets into the function. However, downgrading to 0.5.3 does fix the issue, so it seems to be 0.5.4 related (possibly indirectly).

**Comment by redonkulus** [comment]
> Also, if you go into webpack-core and manually update source-map to the same version does it work?

upgrading this version to 0.5.4 still produces the error.

**Comment by ashaffer** [comment]
Any word on the lines going into this? https://github.com/mishoo/UglifyJS2/blob/45ddb9caeb200615b9f0ced0ed83fa95f0c51b23/lib/output.js#L311

That should give us the info required to create the minimal failing test case.

**Comment by redonkulus** [comment]
@ashaffer here is the additional data from the exception https://gist.github.com/redonkulus/e17a977dbc6a9755ddb6cdd9601336c6

**Comment by ashaffer** [comment]
Ah sorry one more detail: the stack trace from the exception happening there. `ex.stack`

**Comment by redonkulus** [comment]
@ashaffer ok updated. I think we have something here:

```
stack= TypeError: Object 8 has no method 'charCodeAt'
    at isProtoString (/Users/sbertal/Dev/touchdown/touchdown-v2/node_modules/webpack/node_modules/uglify-js/node_modules/source-map/lib/util.js:271:11)
```

**Comment by redonkulus** [comment]
And looks related to the other issue opened today https://github.com/mozilla/source-map/issues/230

**Comment by redonkulus** [comment]
Adding a simple `typeof` check to `isProtoString` fixes the issue, but I'm not sure what other issues that may cause.

**Comment by ashaffer** [comment]
Yep. It shouldn't cause any other issues I don't think. `isProtoString` just wants to know whether or not the string is of the form `\$*__proto__`, which a non-string type can never be.

**Comment by ashaffer** [comment]
PR: #232

**Comment by redonkulus** [comment]
No problem, hopefully that can merged and publish asap. Thanks for helping out!

**Comment by ericf** [comment]
@fitzgen thanks for fixing this!

**Comment by ericf** [comment]
Our builds are back to passing after pulling in 0.5.5, thanks again!
