### ISSUE TITLE
crashing on browser

### ISSUE THREAD

**Issue by pocesar** [mozilla/source-map#233]
Have no idea how this library got included in my build using browserify, but the following line:

https://github.com/mozilla/source-map/blob/7c4905497b5f0a62fd6a3d3f786ba8eac0db4615/lib/util.js#L258

`ReferenceError: identity is not defined`

Breaks everything now. I don't know what library has this as a dependency

**Comment by pocesar** [comment]
Crashing in Firefox 44.0.2, it seems that the `identity` function isn't being hoisted inside blocks, it seems a "regression" in SpiderMonkey

http://statichtml.com/2011/spidermonkey-function-hoisting.html

Declare the function before using it please <3

**Comment by pocesar** [comment]
The dist files seems to be the otherway around from the lib files

https://github.com/mozilla/source-map/blob/7c4905497b5f0a62fd6a3d3f786ba8eac0db4615/lib/util.js#L228 supportsNullProto is defined before it's used

https://github.com/mozilla/source-map/blob/master/dist/source-map.js#L983-L987 dist is showing the functions defined after they are called.

**Comment by borriglione** [comment]
Got the same problem in FF 45.0.2 / Ubuntu

**Comment by fitzgen** [comment]
Fixed in https://github.com/mozilla/source-map/commit/93639790bbae5c4cdaa7093f00636bc0e23a71f2
