### ISSUE TITLE
SourceMap.originalPositionFor and SourceMap.generatedPositionFor should be case insentive to source

### ISSUE THREAD

**Issue by nojvek** [mozilla/source-map#241]

**Comment by tromey** [comment]
Can you explain why?  Nothing in the spec says it should be.  And I wouldn't expect it to be, because URLs are case-sensitive.

**Comment by nojvek** [comment]
I should have been clear. I think it would be great if this was an option in the SourceMap constructor. By default case sensitive, but an api user can choose to use case insensitive version. Wdyt?

Mostly because some tools change the case when generating sourcemap files. Some webservers are case insensitive and I believe some browser devtools handle case insensitivity fine as well.

**Comment by nojvek** [comment]
Also thanks for looking into this and not letting it get lost into the void.

**Comment by tromey** [comment]
It seems to me that consumers of source maps can't know which setting to use.

All that's really required from source maps is internal consistency -- so if a producer changes case, that's fine, as long as it is consistent with what is actually served.

I think one unexpressed idea in the library is that, when looking for source content, the URLs passed to the library should just be ones coming from `sources`.

**Comment by jkrems** [comment]
I'll go ahead and close this issue since it hasn't seen recent activity. I don't see it being implemented anytime soon, realistically.
