### ISSUE TITLE
Broken applied result

### ISSUE THREAD

**Issue by ai** [mozilla/source-map#242]
I uses your awesome `source-map` in PostCSS to generate new source map and apply old to new one (merge them).

I have a report, that result after apply is broken. But I have no idea what I do wrong. Maybe I don’t understand something. Or maybe we really have issue in `source-map` here.
1. [PostCSS source map](https://sokra.github.io/source-map-visualization/#base64,Ym9keSB7CiAgZm9udDogMTAwJSBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7CiAgYmFja2dyb3VuZC1jb2xvcjogI2VmZWZlZjsgfQoKI2JvYXJkIHsKICBwb3NpdGlvbjogYWJzb2x1dGU7CiAgdGV4dC1hbGlnbjogcmlnaHQ7IH0KICAjYm9hcmQgYSB7CiAgICBjb2xvcjogcmVkOyB9CgovKiMgc291cmNlTWFwcGluZ1VSTD1tYXAvYXV0b3ByZWZpeGVkLmNzcy5tYXAgKi8K,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImF1dG9wcmVmaXhlZC5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7RUFDRSxpQ0FBaUM7RUFDakMsMEJBQTBCLEVBQUU7O0FBRTlCO0VBQ0UsbUJBQW1CO0VBQ25CLGtCQUFrQixFQUFFO0VBQ3BCO0lBQ0UsV0FBVyxFQUFFIiwiZmlsZSI6Ii4uL2F1dG9wcmVmaXhlZC5jc3MiLCJzb3VyY2VzQ29udGVudCI6WyJib2R5IHtcbiAgZm9udDogMTAwJSBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7XG4gIGJhY2tncm91bmQtY29sb3I6ICNlZmVmZWY7IH1cblxuI2JvYXJkIHtcbiAgcG9zaXRpb246IGFic29sdXRlO1xuICB0ZXh0LWFsaWduOiByaWdodDsgfVxuICAjYm9hcmQgYSB7XG4gICAgY29sb3I6IHJlZDsgfVxuIl0sInNvdXJjZVJvb3QiOiIuLiJ9,Ym9keSB7CiAgZm9udDogMTAwJSBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7CiAgYmFja2dyb3VuZC1jb2xvcjogI2VmZWZlZjsgfQoKI2JvYXJkIHsKICBwb3NpdGlvbjogYWJzb2x1dGU7CiAgdGV4dC1hbGlnbjogcmlnaHQ7IH0KICAjYm9hcmQgYSB7CiAgICBjb2xvcjogcmVkOyB9Cg==)
2. [Sass source map](https://sokra.github.io/source-map-visualization/#base64,Ym9keSB7CiAgZm9udDogMTAwJSBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7CiAgYmFja2dyb3VuZC1jb2xvcjogI2VmZWZlZjsgfQoKI2JvYXJkIHsKICBwb3NpdGlvbjogYWJzb2x1dGU7CiAgdGV4dC1hbGlnbjogcmlnaHQ7IH0KICAjYm9hcmQgYSB7CiAgICBjb2xvcjogcmVkOyB9CgovKiMgc291cmNlTWFwcGluZ1VSTD1tYXAvbWFpbi5jc3MubWFwICovCg==,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLi4vbWFpbi5jc3MiLCJzb3VyY2VzIjpbIm1haW4uc2NzcyIsIl9iYXNlLnNjc3MiLCJfYm9hcmQuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyJAaW1wb3J0ICdiYXNlJztcbkBpbXBvcnQgJ2JvYXJkJzsiLCJib2R5IHtcbiAgZm9udDogMTAwJSBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7XG4gIGJhY2tncm91bmQtY29sb3I6ICNlZmVmZWY7XG59IiwiI2JvYXJkIHtcblx0cG9zaXRpb246IGFic29sdXRlO1xuXHR0ZXh0LWFsaWduOiByaWdodDtcblxuXHRhIHtcblx0XHRjb2xvcjogcmVkO1xuXHR9XG5cbn1cbiJdLCJtYXBwaW5ncyI6IkFDQUEsQUFBQSxJQUFJLENBQUM7RUFDSCxJQUFJLEVBQUUsMEJBQTJCO0VBQ2pDLGdCQUFnQixFQUFFLE9BQVEsR0FDM0I7O0FDSEQsQUFBQSxNQUFNLENBQUM7RUFDTixRQUFRLEVBQUUsUUFBUztFQUNuQixVQUFVLEVBQUUsS0FBTSxHQU1sQjtFQVJELEFBSUMsTUFKSyxDQUlMLENBQUMsQ0FBQztJQUNELEtBQUssRUFBRSxHQUFJLEdBQ1giLCJuYW1lcyI6W10sInNvdXJjZVJvb3QiOiIuLiJ9,QGltcG9ydCAnYmFzZSc7CkBpbXBvcnQgJ2JvYXJkJzs=,Ym9keSB7CiAgZm9udDogMTAwJSBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7CiAgYmFja2dyb3VuZC1jb2xvcjogI2VmZWZlZjsKfQ==,I2JvYXJkIHsKCXBvc2l0aW9uOiBhYnNvbHV0ZTsKCXRleHQtYWxpZ246IHJpZ2h0OwoKCWEgewoJCWNvbG9yOiByZWQ7Cgl9Cgp9Cg==)
3. [Sass + PostCSS](https://sokra.github.io/source-map-visualization/#base64,Ym9keSB7CiAgZm9udDogMTAwJSBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7CiAgYmFja2dyb3VuZC1jb2xvcjogI2VmZWZlZjsgfQoKI2JvYXJkIHsKICBwb3NpdGlvbjogYWJzb2x1dGU7CiAgdGV4dC1hbGlnbjogcmlnaHQ7IH0KICAjYm9hcmQgYSB7CiAgICBjb2xvcjogcmVkOyB9CgovKiMgc291cmNlTWFwcGluZ1VSTD1tYXAvYXV0b3ByZWZpeGVkLmNzcy5tYXAgKi8K,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIl9iYXNlLnNjc3MiLCJfYm9hcmQuc2NzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTtFQUNFLGlDQUFpQztFQUNqQywwQkFBMEIsRUFDM0I7O0FDSEQ7RUFDQyxtQkFBbUI7RUFDbkIsa0JBQWtCLEVBTWxCO0VBUkQ7SUFLRSxXQUFXLEVBQ1giLCJmaWxlIjoiLi4vYXV0b3ByZWZpeGVkLmNzcyIsInNvdXJjZXNDb250ZW50IjpbImJvZHkge1xuICBmb250OiAxMDAlIEhlbHZldGljYSwgc2Fucy1zZXJpZjtcbiAgYmFja2dyb3VuZC1jb2xvcjogI2VmZWZlZjtcbn0iLCIjYm9hcmQge1xuXHRwb3NpdGlvbjogYWJzb2x1dGU7XG5cdHRleHQtYWxpZ246IHJpZ2h0O1xuXG5cdGEge1xuXHRcdGNvbG9yOiByZWQ7XG5cdH1cblxufVxuIl0sInNvdXJjZVJvb3QiOiIuLiJ9,Ym9keSB7CiAgZm9udDogMTAwJSBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7CiAgYmFja2dyb3VuZC1jb2xvcjogI2VmZWZlZjsKfQ==,I2JvYXJkIHsKCXBvc2l0aW9uOiBhYnNvbHV0ZTsKCXRleHQtYWxpZ246IHJpZ2h0OwoKCWEgewoJCWNvbG9yOiByZWQ7Cgl9Cgp9Cg==)

Look at `#board a` selector, after apply it miss a mapping.

In PostCSS I apply map in [common way](https://github.com/postcss/postcss/blob/master/lib/map-generator.es6#L108):

``` js
let prevMap = new mozilla.SourceMapConsumer(prev.text);
finalMap.applySourceMap(prevMap, from, relativePath(root));
```

[Origin issue](https://github.com/postcss/postcss/issues/814) was created by @winamp and he provided good [playground for this issue](https://github.com/winamp/autoprefixer-sourcemaps).

@fitzgen tell me if you need more information

**Comment by lydell** [comment]
I have managed to reduce this down to a minimal test case:

```js
var sourceMap = require('source-map')

var map = {
  "version": 3,
  "file": "sass.css",
  "sources": [
    "sass.scss"
  ],
  "mappings": "AAAA,AAAA,CAAC,CAAC;EACA,CAAC,EAAE,CAAE,GAIN;EALD,AAEE,CAFD,CAEC,CAAC,CAAC;IACA,CAAC,EAAE,CAAE,GACN",
  "names": [],
  "sourceRoot": ""
}

var consumer = new sourceMap.SourceMapConsumer(map)

console.log(consumer.originalPositionFor({line: 3, column: 2}))
// Actual:
//   { source: 'sass.scss', line: 1, column: 0, name: null }
// Expected:
//   { source: 'sass.scss', line: 3, column: 2, name: null }
```

This [visualization of map in the code above](https://sokra.github.io/source-map-visualization/#base64,YSB7CiAgazogdjsgfQogIGEgYiB7CiAgICBrOiB2OyB9Ci8qIyBzb3VyY2VNYXBwaW5nVVJMPXNhc3MuZXh0ZXJuYWwuY3NzLm1hcCAqLwo=,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2Fzcy5jc3MiLCJzb3VyY2VzIjpbInNhc3Muc2NzcyJdLCJtYXBwaW5ncyI6IkFBQUEsQUFBQSxDQUFDLENBQUM7RUFDQSxDQUFDLEVBQUUsQ0FBRSxHQUlOO0VBTEQsQUFFRSxDQUZELENBRUMsQ0FBQyxDQUFDO0lBQ0EsQ0FBQyxFQUFFLENBQUUsR0FDTiIsIm5hbWVzIjpbXSwic291cmNlUm9vdCI6IiJ9,YSB7CiAgazogdjsKICBiIHsKICAgIGs6IHY7CiAgfQp9Cg==) shows that the character at line 3 column 2 maps back to line 3 column 2.

**Comment by lydell** [comment]
I added this at the end of the code snippet in my last comment:

```js
consumer.eachMapping(function (m) {
  console.log(m)
})
```

<details>
<summary>Here is the output: (click to view)</summary>
```
{ source: 'sass.scss', line: 1, column: 0, name: null }
{ source: 'sass.scss',
  generatedLine: 1,
  generatedColumn: 0,
  originalLine: 1,
  originalColumn: 0,
  name: null }
{ source: 'sass.scss',
  generatedLine: 1,
  generatedColumn: 0,
  originalLine: 1,
  originalColumn: 0,
  name: null }
{ source: 'sass.scss',
  generatedLine: 1,
  generatedColumn: 1,
  originalLine: 1,
  originalColumn: 1,
  name: null }
{ source: 'sass.scss',
  generatedLine: 1,
  generatedColumn: 2,
  originalLine: 1,
  originalColumn: 2,
  name: null }
{ source: 'sass.scss',
  generatedLine: 2,
  generatedColumn: 2,
  originalLine: 2,
  originalColumn: 2,
  name: null }
{ source: 'sass.scss',
  generatedLine: 2,
  generatedColumn: 3,
  originalLine: 2,
  originalColumn: 3,
  name: null }
{ source: 'sass.scss',
  generatedLine: 2,
  generatedColumn: 5,
  originalLine: 2,
  originalColumn: 5,
  name: null }
{ source: 'sass.scss',
  generatedLine: 2,
  generatedColumn: 6,
  originalLine: 2,
  originalColumn: 7,
  name: null }
{ source: 'sass.scss',
  generatedLine: 2,
  generatedColumn: 9,
  originalLine: 6,
  originalColumn: 1,
  name: null }
{ source: 'sass.scss',
  generatedLine: 3,
  generatedColumn: 2,
  originalLine: 1,
  originalColumn: 0,
  name: null }
{ source: 'sass.scss',
  generatedLine: 3,
  generatedColumn: 2,
  originalLine: 3,
  originalColumn: 2,
  name: null }
{ source: 'sass.scss',
  generatedLine: 3,
  generatedColumn: 3,
  originalLine: 1,
  originalColumn: 1,
  name: null }
{ source: 'sass.scss',
  generatedLine: 3,
  generatedColumn: 4,
  originalLine: 3,
  originalColumn: 2,
  name: null }
{ source: 'sass.scss',
  generatedLine: 3,
  generatedColumn: 5,
  originalLine: 3,
  originalColumn: 3,
  name: null }
{ source: 'sass.scss',
  generatedLine: 3,
  generatedColumn: 6,
  originalLine: 3,
  originalColumn: 4,
  name: null }
{ source: 'sass.scss',
  generatedLine: 4,
  generatedColumn: 4,
  originalLine: 4,
  originalColumn: 4,
  name: null }
{ source: 'sass.scss',
  generatedLine: 4,
  generatedColumn: 5,
  originalLine: 4,
  originalColumn: 5,
  name: null }
{ source: 'sass.scss',
  generatedLine: 4,
  generatedColumn: 7,
  originalLine: 4,
  originalColumn: 7,
  name: null }
{ source: 'sass.scss',
  generatedLine: 4,
  generatedColumn: 8,
  originalLine: 4,
  originalColumn: 9,
  name: null }
{ source: 'sass.scss',
  generatedLine: 4,
  generatedColumn: 11,
  originalLine: 5,
  originalColumn: 3,
  name: null }
```
</details>

As you can see, there is a duplicate mapping:

```
{ source: 'sass.scss',
  generatedLine: 3,
  generatedColumn: 2,
  originalLine: 1,
  originalColumn: 0,
  name: null }
{ source: 'sass.scss',
  generatedLine: 3,
  generatedColumn: 2,
  originalLine: 3,
  originalColumn: 2,
  name: null }
```

- The visualizer shows the second mapping, and ignores the first.
- `.applySourceMap()` seems to do it the other way around: Use the first mapping and ignore the second.

Conclusions:

- The visualizer could possibly benefit from somehow showing duplicate mappings.
- This library might want to handle duplicate mappings some way – but how?
- What does the spec say about duplicate mappings?
- Sass shouldn’t output duplicate mappings in the first place. I’ve opened sass/libsass#2122 about that.

**Comment by tromey** [comment]
> This library might want to handle duplicate mappings some way – but how?

I've run into this as well, but I tend to think that the library should work on a GIGO principle.  That is, it can pick either mapping and that's ok -- there's no way to guess which one is more correct.

It would be good, though, to ensure that this library doesn't generate duplicate mappings.

> What does the spec say about duplicate mappings?

Nothing, unfortunately.

**Comment by jkrems** [comment]
Duplicates #61
