### ISSUE TITLE
Uncaught TypeError: Column must be greater than or equal to 0, got -1

### ISSUE THREAD

**Issue by TheSavior** [mozilla/source-map#243]
We have a flake with this symptom:

```
Uncaught TypeError: Column must be greater than or equal to 0, got -1
      at /tmp/81a76371d25387d45b5b0db72f6d0195.browserify:50990 <- ../node_modules/sinon/lib/sinon/spy.js:187:0
```

This flake hasn't occurred consistently enough for us to be able to reproduce it and track it down in any meaningful way. Due to dependency hell, we are stuck using `0.1.32`, we think the source-map dependency via source-map-support via karma-source-map-support (vs the babel dep, or the browserify dep >_<). I'm opening this ticket to see if anyone has seen this before or knows how we can reasonably track down this issue.

Related ticket opened on sinon: https://github.com/sinonjs/sinon/issues/1094
And opened on source-map-support: https://github.com/evanw/node-source-map-support/issues/141

**Comment by psulek** [comment]
@TheSavior Got this error right now. My env: Node v6.9.1, source-map v0.1.32 which is used by source-map-support v0.4.0.

**Comment by jkrems** [comment]
Closing since it seemingly only affected very old versions of `source-map` and it looks like known impacted consumers have upgraded since this issue was opened.
