### ISSUE TITLE
Recursive vs Iterative Implementation on SourceNode.prototype

### ISSUE THREAD

**Issue by wisec** [mozilla/source-map#249]
Several methods in SourceNode.prototype are implemented as recursive.
This could lead to several classical problems such as: 
- Performances
- When tree is too deep it could trigger to Maximum call stack size exceeded exception

In particular: SourceNode.prototype.walk could be really slow on big JS files.

It would be great to implement iteration approach.

Thanks

**Comment by wisec** [comment]
I've tested an iterative version, and it seems to be really slow comparing to the implemented recursive approach. 
I'm going to close the issue as recurision seems to be the best choice atm.
Thanks anyway

**Comment by jasonLaster** [comment]
Thanks for investigating @wisec
