### ISSUE TITLE
SourceMapGenerator.fromSourceMap does not work when mappings is empty

### ISSUE THREAD

**Issue by dmurat** [mozilla/source-map#250]
With TypeScript compiler configured to use `system` modules, I'm getting source maps with empty `mappings` when original files are one liners (i.e. `export * from './some/es6/module';`). These source maps have their `sources` and `sourcesContent` collections filled in correctly. Chrome does not have any problems with such source maps, meaning they are used and displayed correctly.

With such source maps, `SourceMapGenerator.fromSourceMap` returns a generator without `_sources` collection set, which I presume is a bug.

To reproduce this behavior, I added following test in this project:

    // in test/test-source-map-generator.js
    exports['test .fromSourceMap with empty mappings'] = function (assert) {
      var map = SourceMapGenerator.fromSourceMap(
        new SourceMapConsumer(util.testMapEmptyMappings));
      util.assertEqualMaps(assert, map.toJSON(), util.testMapEmptyMappings);
    };

    // in test/utils.js
    exports.testMapEmptyMappings = {
      version: 3,
      file: 'min.js',
      names: [],
      sources: ['one.js', 'two.js'],
      sourcesContent: [
        ' ONE.foo = 1;',
        ' TWO.inc = 2;'
      ],
      sourceRoot: '',
      mappings: ''
    };

I can prepare PR with fix (and some more tests) if this is useful.

**Comment by dmurat** [comment]
[Here](https://github.com/mozilla/source-map/pull/251) is a pull request. Tnx.

**Comment by tromey** [comment]
I believe this was fixed by #251

**Comment by timbell** [comment]
I believe there is a related issue [here](https://github.com/mozilla/source-map/blob/ac518d2f21818146f3310557bd51c13d8cff2ba8/lib/source-map-generator.js#L200).

Something like this would fix it I believe:

`var newSources = this._mappings.toArray().length !== 0 ? new ArraySet() : this._sources;`

**Comment by tromey** [comment]
It would be helpful if you could send that change as a PR with a short test case.

**Comment by timbell** [comment]
Ok, will do so over the weekend
