### ISSUE TITLE
Out of memory error while tries to parse source map

### ISSUE THREAD

**Issue by VitaliyR** [mozilla/source-map#253]
Hi!

I'm using **postcss** (on top of _grunt_) which uses **source-map** to parse sourcemaps. The project it used in is really heavy - about **126 CSS** files with total size about **43MB**. CSS are coming from SASS, and postcss just tries to load them and parse sourcemaps generated by SASS. No any postcss processors are used, just to prove it doesn't related to it. 

I encountered a problem while 'grunting' it - 

`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory`

With the error description:

```
1: _parseMappings(aka SourceMapConsumer_parseMappings) 
[/home/vitaliy/hostroot/clioui/node_modules/grunt-postcss/node_modules/postcss/node_modules/source-map/lib/source-map-consumer.js:~423] 
[pc=0x1e9d743b1aa6] (this=0x1ad8636f0041 <a BasicSourceMapConsumer with map 0x3d66321b1979>,aStr=0x1ad863604101 <Very long string[539601]>,aSourceRoot=0x3a595704101 <null>)
```

The interesting here is `Very long string` in `source-map-consumer.js`. It seems that it tries to load  sourcemap of big CSS file and die because of memory overflow. 

Can you help me with this one? Where should I search? Maybe I need to provide some additional details?

**Comment by jkrems** [comment]
It will be hard to debug this without a clear test case. Closing because there hasn't been any activity. If we get a clear test case, we could likely reopen.
