### ISSUE TITLE
Possible error caused by oversight in source-map-generator.js#L264

### ISSUE THREAD

**Issue by Lange** [mozilla/source-map#263]
In [source-map-generator.js#L264](https://github.com/mozilla/source-map/blob/master/lib/source-map-generator.js#L264), a check is made to see if `aOriginal` is falsey. However, I don't think this is ever possible, because `aOriginal` is always an object.

Instead, I think that this should check to see if `aOriginal.line === null && aOriginal.column === null`. When I did this, it seemed to make some pretty nasty errors like https://github.com/Polymer/polymer-bundler/issues/516 go away.

Am I understanding this code correctly? Should I go ahead and open a pull request?

**Comment by tromey** [comment]
I think this can be closed now that #265 was merged.
Please reopen if I'm mistaken about this.
