### ISSUE TITLE
idea: improve performance with inspiration from https://github.com/krisselden/fast-source-map

### ISSUE THREAD

**Issue by MagicDuck** [mozilla/source-map#270]
Would any of the ideas here help with improving performance? Like using buffers, etc.
https://github.com/krisselden/fast-source-map
They say they are 10x faster than source-map for decoding...

**Comment by tromey** [comment]
I'm fully in favor of performance improvements.  I was thinking of boosting VLQ decoding speed using WebAssembly and https://github.com/tromey/vlq (though that library is insufficient, one would also want the mappings to be handled).

**Comment by cspotcode** [comment]
Re: their use of buffers:
I benchmarked fast-source-map with and without converting the mappings string to a buffer.  It's actually faster without converting.  So I think we'd only get a performance boost if the input was already a buffer, which would mean using a custom JSON parser that operates directly on buffers.

**Comment by aleclarson** [comment]
This library now uses WASM: https://hacks.mozilla.org/2018/01/oxidizing-source-maps-with-rust-and-webassembly/

This issue can probably be closed.

**Comment by tromey** [comment]
I'm inclined to agree, so I'm closing it.  If there's still something to be done, post some details here and we can reopen it.  Thanks.
