### ISSUE TITLE
"typings" field in package.json is broken

### ISSUE THREAD

**Issue by alexeagle** [mozilla/source-map#273]
the `typings` field was added by
https://github.com/mozilla/source-map/commit/6f5d5946d022312f41433c8f847635427ed2e854
which also added `source-map.d.ts`, however that file wasn't included in the published package:
https://unpkg.com/source-map@0.5.7/

```
foo.ts(1,21): error TS7016: Could not find a declaration file for module 'source-map'. '/usr/local/google/home/alexeagle/Projects/repro_source-map/node_modules/source-map/source-map.js' implicitly has an 'any' type.
  Try `npm install @types/source-map` if it exists or add a new declaration (.d.ts) file containing `declare module 'source-map';`
```

/cc @tbosch

**Comment by tromey** [comment]
Is it sufficient to add `source-map.d.ts` to the `files` array in `package.json`?

**Comment by alexeagle** [comment]
I would guess the build needs to be modified to copy the source-map.d.ts into the dist folder before publishing.

**Comment by tromey** [comment]
If I `npm install source-map`, what's installed includes everything from `files`, so I think it's fine to just list it.

**Comment by alexeagle** [comment]
It doesn't matter what `npm install` does if the file isn't published to NPM

**Comment by tromey** [comment]
I don't understand.  The idea of the patch is that the things in files are published, so (1) fix up the file list, and then (2) publish to npm.  https://docs.npmjs.com/files/package.json claims that this should be sufficient.  Or is there some other scenario that's important that I don't know of?

**Comment by alexeagle** [comment]
Yes, that sounds right. I'm not familiar with the publishing steps here - in some of our repos we run `npm publish` from the dist folder so that would be broken. Also there could be .npmignore to control what is published, but don't have one here. The real test is to run `npm publish` in dry-run mode, which seems to be `npm pack`

**Comment by tromey** [comment]
Thanks for mentioning `npm pack`.  I confirmed that this works.
