### ISSUE TITLE
ChangeLog for 0.6 and 0.6.1

### ISSUE THREAD

**Issue by ai** [mozilla/source-map#291]
ChangeLog for breaking changes 0.6 release is missed. Is it safe to update PostCSS?

**Comment by GeoffreyBooth** [comment]
Apparently there are some pretty serious breaking changes that can break your builds: https://github.com/meteor/meteor/issues/9217

An updated changelog with some explanation would be most welcome! Especially including what we can do to avoid these validation errors crashing our builds.

**Comment by jkrems** [comment]
There is a change log now that contains entries for 0.6 and up. (Also 👋  @GeoffreyBooth of the past)
