### ISSUE TITLE
Typings missing toJSON

### ISSUE THREAD

**Issue by kitsonk** [mozilla/source-map#294]
The `SourceMapGenerator` has a `.toJSON()` method on its prototype:

https://github.com/mozilla/source-map/blob/d0d00a626d3bb8e5e2cebba727cf64c821f3b70c/lib/source-map-generator.js#L398

But the typings included do not reflect that:

https://github.com/mozilla/source-map/blob/d0d00a626d3bb8e5e2cebba727cf64c821f3b70c/source-map.d.ts#L70-L77

**Comment by kitsonk** [comment]
Resolved by 8c732cd992b7a5b9a642fa22a128ff3a4a148af5

**Comment by tromey** [comment]
Sorry, I should have checked that.

**Comment by kitsonk** [comment]
No problem, a fix is a fix! Thank you...
