### ISSUE TITLE
Release notes not up to date

### ISSUE THREAD

**Issue by simondel** [mozilla/source-map#305]
Hi! I got notified by [dependabot](https://dependabot.com/) that my dependency on source-map is out of date. However, I cannot find updated release notes as the one in the [repo](https://github.com/mozilla/source-map/blob/master/CHANGELOG.md) still points to 0.5.6. as the latest version.

Where could I find an updated changelog?

**Comment by jkrems** [comment]
The changelog contains entries for versions past 0.5.6 now: https://github.com/mozilla/source-map/blob/master/CHANGELOG.md. Please note that minor versions increases during `0.x` may contain breaking changes in semver.
