### ISSUE TITLE
Typings mismatch

### ISSUE THREAD

**Issue by Brocco** [mozilla/source-map#307]
**Issue**
The version of typings currently within the [master branch](https://github.com/mozilla/source-map/blob/master/source-map.d.ts#L314) do not match the version which are currently published to [npm](https://unpkg.com/source-map@0.6.1/source-map.d.ts).

**Expected behavior**
As a TypeScript consumer of this package, I would expect the typings to match the version in the repo.

**Comment by tromey** [comment]
I don't know anything about TypeScript, so you'll have to bear with me a bit.

My first thought here was that the file in git can't always be used with some published version of the package, because git changes, whereas a published version does not.  But maybe the issue is that the published file is incorrect somehow?

Anyway - what fix would be correct here?

**Comment by Brocco** [comment]
Ahhhh.... I see the issue... it is a timing issue, this [commit](https://github.com/mozilla/source-map/commit/7c06ac83dd6d75e65f71727184a2d8630a15bf58#diff-7945f6bb445d956794564e098ef20bb3) (Oct 13) was made after the latest release (Sep 29).

So to correct myself in what I'm requesting... can a release be made of this package?

**Comment by hansl** [comment]
@tromey Typescript uses the version that comes with the code. If your code was installed using `npm`, then it's whatever type definition was released as part of your release process. As Mike said, all you need at this point is another release that contains the latest `.d.ts` file.

**Comment by alexeagle** [comment]
@Brocco the commit in question was released in 0.7.1 so I think this can be closed.

(However there were also breaking changes eg. SourceMapConsumer now has an async constructor (??) so it's not easy to pick up the fix...)

**Comment by Brocco** [comment]
Thanks @alexeagle
