### ISSUE TITLE
v0.7 is breaking change for Node < 8 users

### ISSUE THREAD

**Issue by TheLarkInn** [mozilla/source-map#310]
Is there any way we can publish this as a SemVer Major? Considering this would be breaking for Node 6 users, etc.

**Comment by fitzgen** [comment]
Below 1.0.0, isn't 0.7.0 a breaking change bump to 0.6.X?

**Comment by t-sauer** [comment]
To my knowledge this is actually how semver is supposed to work. Pre 1.0.0 releases have no semver guarantees in general (see https://semver.org/#spec-item-4). This should also be no problem for npm/yarn users since `^0.6.0` would only install 0.6.x versions.

**Comment by TheLarkInn** [comment]
Thanks for the clarification. Sorry for the confusion. Looking to pin down
what we need to for webpack/webpack-sources etc. Currently we don't have an
engines flag but this will change as webpack 4 will drop node 4 support but
still support v6. And of course we'd love to leverage the wasm module if
users have the right node version.

Thanks!

**Comment by kflorence** [comment]
NPM shrinkwrap FTW

**Comment by TheLarkInn** [comment]
We have yarn.lock files so we should be good on that regard! Thank you!! Closing!
