### ISSUE TITLE
Document how to depend on source-map 0.6.X for old nodes and 0.7.0 for new nodes

### ISSUE THREAD

**Issue by devongovett** [mozilla/source-map#313]
We're currently working on source map support in Parcel: https://github.com/parcel-bundler/parcel/pull/506. We'd love to take advantage of the WASM version of source-map in 0.7, but we also need to support Node < 8 users. Is there a way the source-map library could fall back to a JS version for Node < 8 users?

**Comment by jbernalvallejo** [comment]
+1

**Comment by Daweo93** [comment]
+1

**Comment by rewmike** [comment]
+1

**Comment by fitzgen** [comment]
I have no interest maintaining two versions of source map parsing and querying, nor incurring the additional code size bloat.

I suggest using the old version of the library if you have to support old node versions, or alternatively setting up some kind of feature detection scheme.

I'll leave this issue open for adding documentation on how to depend on 0.6.X for old nodes and 0.7.0 for new ones.

**Comment by deadalusai** [comment]
For client code, adding the following snippet to `package.json` will pin `source-map` to 0.6.x versions:
```
"resolutions": {
    "source-map": "~0.6.1"
}
```
This may be useful while we wait for downstream packages to update for the changes in 0.7.0 (or pin to 0.6.x)

**Comment by fimius23** [comment]
Why doesn't this project follow [semver](https://semver.org/) so that I'm protected from this version?

**Comment by tromey** [comment]
> Why doesn't this project follow semver so that I'm protected from this version?

It does; semver treats major version 0 specially.  I think it would probably be a good idea to just admit that this package is heavily used and release 1.0.

**Comment by fitzgen** [comment]
That sounds good to me

**Comment by jkrems** [comment]
In the meantime node <8 has become less relevant (I'll claim) and `@parcel/source-map` has been published. I'll close this issue but leave https://github.com/mozilla/source-map/issues/331 open which is somewhat related.
