### ISSUE TITLE
Angular CLI Build Failed with Unexpected token: operator (>) 

### ISSUE THREAD

**Issue by kamprasad2007** [mozilla/source-map#317]
Environment:
angular/cli : 1.0.3
node : 6.11.1
os : win32 x64

When executing  **ng build -aot false -prod** it gives following error.

> ERROR in vendor.394aa10abde0566efdcb.bundle.js from UglifyJs
> Unexpected token: operator (>) [vendor.394aa10abde0566efdcb.bundle.js:56810,35]

After investigation found out that source-map V0.7.0 is the issue and when downgrade to 0.6.1 it works as expected. Anyone face this issue?

**Comment by fitzgen** [comment]
Thanks for filing an issue.

> node : 6.11.1

Note that source-map >= 0.7.0 requires node >= 8: https://github.com/mozilla/source-map/blob/master/package.json#L57

As far as UglifyJS goes, it does not support modern ECMAScript, which this library uses. From their README:

> uglify-js only supports ECMAScript 5 (ES5).

You could use babel first, or try closure compiler.
