### ISSUE TITLE
TypedError in wasm.js

### ISSUE THREAD

**Issue by c-niederer** [mozilla/source-map#319]
**ISSUE**
When executing a TypeError occurs in _wasm.js_ because a callback is null.

**EXPECTED**
A defined callback.

**STEPS TO REPRODUCE**
- run `npm install`, `npm run build` and `npm run exec`

This issue came up after porting the code to source-map@0.7.0.

Sample code can be found [here](https://github.com/c-niederer/source-map-bug).

**Comment by fitzgen** [comment]
Thanks for filing an issue!

**Comment by fitzgen** [comment]
Fixed in https://github.com/mozilla/source-map/pull/330
