### ISSUE TITLE
Create a branch for 0.6.x?

### ISSUE THREAD

**Issue by realityking** [mozilla/source-map#324]
I read @mraleph's [blog post](http://mrale.ph/blog/2018/02/03/maybe-you-dont-need-rust-to-speed-up-your-js.html) about optimizing source-map parsing without WASM earlier this morning. Since 0.6.x will be used for a long time in the Node.js ecosystem.

I'd love to apply some of his lessons to the code base. Would you be open to creating a 0.6.x branch to send pull requests against and eventually releasing a 0.6.2?

**Comment by kurtextrem** [comment]
He also posted the following graphs:
![dwbtbvuw0aariqb](https://user-images.githubusercontent.com/502146/36413477-de1882c2-161e-11e8-9dab-531868905e5c.jpg)
![dwbtbvuwaaavkn-](https://user-images.githubusercontent.com/502146/36413478-de351f68-161e-11e8-9260-3d52a14ac1c3.jpg)

**Comment by fitzgen** [comment]
As of #325, the Rust+Wasm is another 3x faster. See http://fitzgeraldnick.com/2018/02/26/speed-without-wizardry.html for details.

**Comment by realityking** [comment]
Hey @fitzgen, That's great - and I look forward to using it myself. But there are a lot of projects out there who will be relying on the 0.6 series for the next ~1 year until Node.js 6 is out of support. It would be great it those projects could benefit from the work already done by @mraleph.

I'm not at all advocating to abandon the WASM efforts, but the wider Node.js ecosystem is not ready to drop support for Node.js 6.

**Comment by 7rulnik** [comment]
I ported optimizations from the article into https://github.com/7rulnik/source-map-js
This fork 400% faster in parsing and 30% faster in serializing
