### ISSUE TITLE
No longer working with ReactNative

### ISSUE THREAD

**Issue by badams** [mozilla/source-map#327]
0.6.1 was working with ReactNative, but since then the dependency on the node `fs` module has been introduce and is no longer working.

The bundler will complain when trying to generate our bundle

```
error: bundling failed: Error: Unable to resolve module `fs` from `/Users/xxx/node_modules/source-map/lib/read-wasm.js`: Module does not exist in the module map
```

**Comment by fitzgen** [comment]
Thanks for filing an issue. The 0.7.X series depends on `fs` to load the wasm, so maybe you can polyfill it or something.
