### ISSUE TITLE
Allow async functions

### ISSUE THREAD

**Issue by hildjj** [mozilla/source-map#337]
Are we still limited to an old version of acorn as implied by [this comment](https://github.com/mozilla/source-map/blob/adfd0fbf77a55166070b314492046772291622d0/lib/source-map-consumer.js#L67)?

**Comment by fitzgen** [comment]
Not sure!

**Comment by tromey** [comment]
Sounds like it is fixed: https://github.com/webpack/webpack/issues/2872

**Comment by hildjj** [comment]
I tried it and it worked.  After we decide #336 is ok, I may take an async pass.  Let's leave this bug open for that.
