### ISSUE TITLE
Segments with a null source

### ISSUE THREAD

**Issue by aleclarson** [mozilla/source-map#346]
I have a question regarding inserted code (segments with a null source). It's not specific to this library, but I figured you folks have experience with this.

AFAIK, there's currently no support for identifying code that isn't associated with a source file. The solution I've found is to include a `null` literal in the `sources` array, and have a segment's source index point to it. Another idea is for the segment to only have a generated column (no source index, line, or column). These would indicate a character range that cannot be traced to a source file.

Without a null source, I don't think there's a way for source map consumers to detect character ranges that have no source file. The inserted code is assumed to be part of the closest segment with a lesser source column [(at least in Chrome devtools)](https://chromium.googlesource.com/chromium/blink/+/master/Source/devtools/front_end/sdk/SourceMap.js#196). This leads me to believe there is a necessity for `null` sources in source maps (and libraries like this should support it), but perhaps I'm mistaken and this is a non-issue?

Maybe I missed it, but there isn't anything about this in the spec.

Hope I'm being clear, and sorry if these questions are not welcome here. ✌️

**Comment by fitzgen** [comment]
The firefox debugger will keep stepping until it reaches a location that maps to an original source, so if you generate a segment without original location info, the debugger will skip through it.

On the other hand, if you generate a synthetic source and put it into the `sources`, the debugger should pause there and let users debug the synthetic source.

I don't know whether other debuggers treat this the same way.

The `sources` array is expected to have only strings. I wouldn't be surprised if downstream tooling chokes on `null` in there.
