### ISSUE TITLE
Feature request: Support mappings[] for multiple line ranges

### ISSUE THREAD

**Issue by cookiengineer** [mozilla/source-map#353]
Currently, AFAIK and as far as the kind of (un?)official spec hosted at https://sourcemaps.info/spec.html goes, source maps is very limited in the use case of using it to map multiple concat'ed files in a simple manner.

For example, when comparing file sizes this is very typical when just concating files together and generating a source map file for it:

```bash
[$] ls -la
total 276
drwxr-xr-x 2 cookiengineer users   4096 Aug 21 17:04 .
drwxr-xr-x 8 cookiengineer users   4096 Aug 21 17:04 ..
-rw-r--r-- 1 cookiengineer users 211617 Aug 21 17:04 dist.js
-rw-r--r-- 1 cookiengineer users  59032 Aug 21 17:04 dist.js.map
```

The underlying issue is that 1:1 mappings of lines seemingly always need a separate `AACA;` entry per-line when there's actually no change in the mapping from `sources` to the `file`.

My personal questions are now:

- [ ] Are the `AACA;` per line actually necessary? If not, what reflects a 1:1 line mapping instead?
- [ ] Why can't `mappings[]` be just an Array of line numbers or line ranges?

Something like this would be far more efficient and very very easy to compute, compared to the current format specification:

```javascript
{
  "version": 1337,
  "file": "/build/dist.js",
  "sources": [
    "/source/first.js",
    "@some-injected-code.js",
    "./source/second.js",
    "./source/third.js"
  ],
  "mappings": [
    [ 2000 ], // assuming that first.js is exactly 2000 lines long
    [ 13 ], // injected code is 13 lines long
    [ 20, 100 ], // only line 20 to 100 is contained in "file"
    [ [ 10, 20 ], [ 22, 30 ] ] // two chunks from ./source/third.js
  ]
```

**Comment by jkrems** [comment]
This repository is just one implementation of the spec ([official spec location is a Google Doc](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit)). But on the other hand there is no longer a discussion list around the spec (the link in the doc is broken).

/cc @concavelenz Is there a place to ask about source maps?

**Comment by jkrems** [comment]
Looks like the link could just be updated to point to the new location of the email list: https://groups.google.com/g/mozilla.dev.js-sourcemap
