### ISSUE TITLE
`originalPositionFor` is off by one on the column

### ISSUE THREAD

**Issue by SimenB** [mozilla/source-map#359]
See reproduction repo: https://github.com/SimenB/sourcemap-issues

Happy to open up an issue with Babel if the sourcemap from them is wrong

**Comment by loganfsmyth** [comment]
Source maps don't operate at that resolution. Babel's mappings map the word `it` to `it` in the output code, but the fact that they are the same variable and a one-character offset in one is probably reflective of a one-character offset in the original file is not known. All it knows is that the range over the generated code (`17:2` => `17:4`) contains `17:3` and maps to `15:2` in the original file.

**Comment by jkrems** [comment]
I assume that this question has been answered (it gives the beginning of the original range but doesn't make assumptions about sub-offsets inside of the mapped ranges).
