### ISSUE TITLE
`sourceMapURL` cannot be a `data:` URL

### ISSUE THREAD

**Issue by demurgos** [mozilla/source-map#373]
Hi,
I am using `SourceMapConsumer.with` to read source maps. On of the arguments is `sourceMapURL`. When I pass a `data:` url, the library throws an error. I expect it to work.
I am using Node `11.2.0`.

Example URL:
```
data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoibWFpbi5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm1haW4udHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUlBLFNBQVMsS0FBSyxDQUFDLEVBQWdCO1FBQWYsY0FBSTtJQUNsQixPQUFPLENBQUMsR0FBRyxDQUFDLFlBQVUsSUFBSSxNQUFHLENBQUMsQ0FBQztBQUNqQyxDQUFDO0FBRUQsS0FBSyxDQUFDLEVBQUMsSUFBSSxFQUFFLEtBQUssRUFBQyxDQUFDLENBQUMifQ==
```

This issue is present in both the version `0.7.0` and `0.8.0-beta.0`.

In `0.8.0-beta.0`, the error happens in the `trimFilename` function.

https://github.com/mozilla/source-map/blob/11cecea2b64ead3f93cde37a5789dc7683685a7c/lib/util.js#L293-L301

I get:
```
TypeError [ERR_INVALID_URL]: Invalid URL: .
```

My current workaround is to pass `undefined` as the `sourceMapURL` parameter but I'd prefer to be able to safely pass the `sourceMapURL` from [the ScriptParsed event](https://chromedevtools.github.io/devtools-protocol/tot/Debugger#event-scriptParsed).

**Comment by loganfsmyth** [comment]
That argument represents the URL to the map file, not the map itself. It is used as the base path for the `sources`items in the map provided in the first argument.

In your context, you'd want to decode the data URL first, and then pass that value as the first argument.

It does seem like it would be ideal of the `source-map` library provided utilities for decoding `//# sourceMappingURL=` comments and such, but it does not at the moment.

**Comment by loganfsmyth** [comment]
The argument represents the conceptual location of the map. In this context, the `sources` entries in the source-map data should be resolved relative to is the `main.js` file URL, not the `data:` URL, so it is the URL of `main.js` that you would pass as that argument.

`data:` URLs are not valid base URLs, because there is no concept of a path relative to a `data:` URL.

**Comment by loganfsmyth** [comment]
> Do you mean that in the case of a data: URL, I should pass the URL of the generated file instead?

Yep!

> decide itself how to perform the resolution.

Yeah, I think there a lot of improvements that can be made to the UX of the library. Hopefully I'll be able to find some time for that in the future.

**Comment by demurgos** [comment]
Thanks. I was thrown off by the argument name/documentation, but this discussion cleared things up. I'll close the issue since it's not actionable at the moment and a better UX may come some day.
