### ISSUE TITLE
Unable to resolve source-map issue in closure-loader

### ISSUE THREAD

**Issue by vmonisha69** [mozilla/source-map#380]
ERROR in ./content/closure-polyfill.js
Module build failed: TypeError: aSourceMapConsumer.eachMapping is not a function

**Comment by loganfsmyth** [comment]
It is hard to say without a stacktrace. Perhaps the wrong version of `source-map` is being loaded?

**Comment by jkrems** [comment]
Closing since we're lacking a clear reproduction / test case for this error.
