### ISSUE TITLE
Possible to remove comments in source maps?

### ISSUE THREAD

**Issue by btsheehy** [mozilla/source-map#381]
In regards to this discussion: https://twitter.com/btsheehy/status/1104052415584702465

Is it possible to remove comments from source maps before you ship them to production? 

I think it's more popular now to ship your source maps to prod to encourage people to learn from production code, but I could see devs being hesitant to do this if it means shipping their comments as well, whether that's for reasons like mentioned in that thread, or PR reasons of not wanting your developers unfiltered and potentially snarky/vulgar code comments going public.

**Comment by loganfsmyth** [comment]
The sourcemap spec is relatively language-agnostic, so this isn't something I'd expect to be the responsibility of this library. 

Whatever build process you are using could certainly preprocess code to remove the comments before it is inserted into the sourcemap though.
