### ISSUE TITLE
Way to end `eachMapping` early?

### ISSUE THREAD

**Issue by mheiber** [mozilla/source-map#389]
It doesn't look like there is a way to end `eachMapping` early.
We have some code that searches through the mappings for a 'bad' mapping. We want to exit the function early at that point, instead of continuing through all the other mappings.

Would you accept a PR to add this functionality? Could be implemented as:
- a `done` callback
- or `return false` to stop the iteration
- or `return END_ITERATION` where `END_ITERATION` is defined as  a special value `{}`. This has better backwards-compatibility than returning `false`.

**Comment by adjenks** [comment]
In the meantime, a hack could be to throw an exception and then catch it. Or just do no operation when the line isn't the one you want. It's similar to a forEach loop in javascript, there's no way to exit except for throwing an error.
If you're looking for a specific line though, I'm not sure why you didn't use "originalPositionFor", it returns the same info for one particular line.

**Comment by mheiber** [comment]
closing, see [@adjenks ' suggestions](https://github.com/mozilla/source-map/issues/389#issuecomment-646235690)
