### ISSUE TITLE
Convertin minified build stack traces to source in the browser

### ISSUE THREAD

**Issue by carpben** [mozilla/source-map#401]
I'd like to convert minified stack errors to source code stack trace, in the browser using the sourceMap. It's a create-React-App project, which uses Webpack behind the hood. And it also uses code splitting. According to source-map's documentation a SourceMapConsumer object should be initialized with a url to a "lib/mappings.wasm" file. But I coulnd't find such a file in the build folder, or anywhere else in the project.

**Comment by freemaths** [comment]
Exactly the same issue.
I have both the source maps and js but no .wasm file. 
I would like to debug live issues but need to convert the stack traces (e.g. static/js/main.03e473e9.chunk.js:1:222110)
Did you figure out a way?

**Comment by delneg** [comment]
https://github.com/mozilla/source-map/blob/master/lib/mappings.wasm
Also, you can compile it yourself from https://github.com/fitzgen/source-map-mappings

**Comment by freemaths** [comment]
@delneg many thanks

It looks to work fine for some create-react-app javascript chunks but not others. Any idea what I might need to do? Is it likely to be code in ./src which has a problem? Do I have to custom build a wasm file?

main.084ddbfe.chunk.js.map starts {"version":3,"sources":["UI.js","Utils.js","evaluate.js","normal.js",...
2.f5722ef6.chunk.js starts {"version":3,"sources":["../node_modules/react/jsx-runtime.js","../node_modules/react/index.js",...

source: main.084ddbfe.chunk.js line: 1 column 224095
source: line: column
source: 2.f5722ef6.chunk.js line: 2 column 493843
source: ../node_modules/react-bootstrap/esm/createWithBsPrefix.js line: 21 column 26 name: className
source: 2.f5722ef6.chunk.js line: 2 column 494187
source: ../node_modules/react-bootstrap/esm/ModalDialog.js line: 7 column 22 name: bsPrefix
source: 2.f5722ef6.chunk.js line: 2 column 488636
source: ../node_modules/react-overlays/esm/Modal.js line: 51 column 23 name: show
source: 2.f5722ef6.chunk.js line: 2 column 496099
source: ../node_modules/react-bootstrap/esm/Modal.js line: 49 column 22 name: bsPrefix
source: main.084ddbfe.chunk.js line: 1 column 7946
source: line: column
source: main.084ddbfe.chunk.js line: 1 column 261452
source: line: column
source: main.084ddbfe.chunk.js line: 1 column 273103
source: line: column
source: main.084ddbfe.chunk.js line: 1 column 272261
source: line: column
source: main.084ddbfe.chunk.js line: 1 column 6959
source: line: column
source: main.084ddbfe.chunk.js line: 1 column 316522
source: line: column

**Comment by jkrems** [comment]
The issue is likely not related to the build of the wasm file (it contains generic logic to look up source mappings). If you have problems with a specific source map, it may be easier to create a separate issue with a minimal reproduction (just using the `source-map` library directly with that source map).
