### ISSUE TITLE
Webpack URLs are corrupted by normalization

### ISSUE THREAD

**Issue by lorenzodallavecchia** [mozilla/source-map#406]
The URLs representing the original source files that get bundled by webpack are corrupted by `source-map`, becoming different from the URLs in the source map.
Among other things, this makes clicking the URLs not work in Chrome developer tools, making tools like [source-map-support](https://www.npmjs.com/package/source-map-support) less useful.

## Steps to reproduce

1. Clone the [test repository](https://github.com/lorenzodallavecchia/sourcemap-bug-normalized-url).
2. `npm install`
3. `npm start`
4. Open Chrome at the indicated URL and look at the DevTools console

## Actual result

Looking at the console, you should see a URL pointing at a source-code location. If you click the URL, it opens a blank tab instead of jumping to the source file in DevTools.

## Expected result

Clicking the URL should open the `helpers.js` file in DevTools.

# Thoughs

This is happening because the path in the URL returned by `source-map` does not match the one in the mappings.

- *URL in mappings*: `webpack:///./src/helpers.js`
- *URL returned*: `webpack:///src/helpers.js`

The culprit seems to be the URL normalization that `source-map` does internally, which is removing `.` and `..` references in the path.

My idea is that the normalization is fine in `http`, `file` and other schemes whose semantic is well defined, but should not be attempted for custom schemes. In the case of `webpack` and `webpack-internal`, the URLs are purely symbolic (the physical file does not exist), so I thnk they should be left intact.

Also, this problem is similar to #267. In that case, the corrupted part were the leading three slashes (`///`) and it was fixed by not altering them any more.

**Comment by loganfsmyth** [comment]
> This is happening because the path in the URL returned by source-map does not match the one in the mappings.

To be sure I follow, you're saying that if you log the URL with the `./` in it, Chrome links it properly, is that correct?

I can definitely see this being frustrating, but to me it seems more like something that Chrome would be up responsible for handling. Mainly because you said:

> the URLs are purely symbolic

and I don't think that is realistically the case. The behavior of URLs are well specified by https://url.spec.whatwg.org and that includes arbitrary URL schemes. Something that is "purely symbolic" would generally be represented in a URL the same way a `data:` or `blob:` URL would be, e.g. `webpack:./src/helpers.js`, which treats everything after the `:` as essentially random URL-encoded data.

It seems like Chrome should normalize the URL before checking whether it matches a file in DevTools, since that normalization behavior is well-defined by the URL spec.

**Comment by lorenzodallavecchia** [comment]
> To be sure I follow, you're saying that if you log the URL with the ./ in it, Chrome links it properly, is that correct?

Yes @loganfsmyth, Chrome is behaving that way.
Apparently, an additional `.` directory makes the difference, hence my reasoning that Chrome is treating the URLs "symbolically".

You have a point in saying that Chrome should be more lenient and normalize the useless `.`.
I will probably file an issue on Chromium and see what they think.

However, I see at least one problematic case for which we cannot blame Chrome.
If the source-mapped path is outside the source map root directory, the path will contain a series of leading `..` directories.

For example, suppose that my project sources are organized this way, maybe because I use a monorepo.

```
node_modules
  foo
    foo_main.js
packages
  main
  utils
    src
      index.js
```

If I `require("foo")` from _index.js_ and run webpack using _src_ as context, the source-mapped URL of the main package would be

```
webpack:///../../node_modules/foo/foo_main.js
```

In this case, `source-map` would normalize it to `webpack:///node_modules/foo/foo_main.js`, breaking the link and possibly conflicting with another module installed at that location.

I think the problem here is that `webpack:` URLs, do not use a root that is guaranteed to contain all files. Some files may be located outside of the mapped root.

**Comment by loganfsmyth** [comment]
> I think the problem here is that webpack: URLs, do not use a root that is guaranteed to contain all files. Some files may be located outside of the mapped root.

I'm not sure that's something that can be resolved here. URLs has a specified behavior and in the case of `webpack:///../../node_modules/foo/foo_main.js`, Webpack is generating a path that has a meaning other than what it intended. You'd either need to set an explicit `context` to your monorepo root (which would be my recommendation), or override `devtoolModuleFilenameTemplate` in your Webpack config with something that points from the repo root to the context path.

**Comment by lorenzodallavecchia** [comment]
You are absolutely right @loganfsmyth.
I read the relevant RFC about the simplification of `.` and `..` and it is indeed standard behavior for URLs that contain slashes.

I think the situation is that webpack is spitting out non-standard URLs and Chrome happens to be lenient enough to accept them.

Going forward I will probably use a custom `devtoolModuleFilenameTemplate` function and fix the path hierarchy.

Thanks for helping me sort this out.
