### ISSUE TITLE
Dead link in readme

### ISSUE THREAD

**Issue by richardgarnier** [mozilla/source-map#421]
The readme starts with:
- This is a library to generate and consume the source map format [described here](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit).

However the google document was apparently removed and is currently inaccessible.

**Comment by chbrown** [comment]
Same but for me Google says "this item [...] is in violation of our Terms of Service" :(

Screenshot from just now:
![20201002T144709-Screenshot](https://user-images.githubusercontent.com/360279/94959037-8107c700-04be-11eb-9699-dd6532a26dbf.png)

**Comment by jkrems** [comment]
The doc is back now and the link should work again.
