### ISSUE TITLE
TypeScript definitions are missing SourceMapConsumer.initialize

### ISSUE THREAD

**Issue by jlfwong** [mozilla/source-map#423]
Hi! 

The `SourceMapConsumer` interface defined in [`source-map.d.ts`](https://github.com/mozilla/source-map/blob/7a263408de1b60e60b6220ca3e36d9b3e4aa047d/source-map.d.ts#L82) is missing a definition for `initialize`. I think all that's needed is:

```
initialize({"lib/mappings.wasm": string | ArrayBuffer}): void
```

Would you accept a PR for this? I'm not sure what the right comment to put above it would be.

**Comment by reduxdj** [comment]
Hello... it's been a few months, this is a blocker for me too.

**Comment by jkrems** [comment]
I think a PR for that would be appreciated!

**Comment by andersonvom** [comment]
@jkrems I just noticed that `source-map.d.ts` was indeed missing an entry for that function and submitted the PR above. I'd be glad to make any changes if necessary.
