### ISSUE TITLE
I can't access the source map format

### ISSUE THREAD

**Issue by hamzahamidi** [mozilla/source-map#424]
Hello,
I can't access the source map format. Maybe the link is broken in the description https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit

![image](https://user-images.githubusercontent.com/22576950/95320530-e3cfd880-0899-11eb-8969-85d01cb79c4c.png)

**Comment by loganfsmyth** [comment]
Huh, not sure why that would have been taken down, but the same info is hosted at https://sourcemaps.info/spec.html

**Comment by hamzahamidi** [comment]
Thanks for the information
