### ISSUE TITLE
Environment detection broken in Node 18

### ISSUE THREAD

**Issue by lukastaegert** [mozilla/source-map#460]
This package uses

```js
if (typeof fetch === "function") {
  // ...
}
```

to detect if it is running in a browser environment. This no longer works in latest Node as `fetch` is now available as a regular Node global. I currently use `delete global.fetch` in my code to work around this, but it would be preferable if it uses a better environment sniffing algorithm, e.g. by checking for for Node-only globals.

**Comment by eemeli** [comment]
Duplicate of #349.
