### ISSUE TITLE
Reference to License.txt 

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [mozilla/source-map#487]
At https://github.com/mozilla/source-map/blob/master/source-map.js#L3 you have:
```
 * Licensed under the New BSD license. See LICENSE.txt or:
 * http://opensource.org/licenses/BSD-3-Clause
```

But you do not have any `LICENSE.txt` at your root, it is `LICENSE` instead (and nor was it anytime in the past apparently).
It's probably minor but would be nice to change this to `LICENSE` since I assume that is what the notice was referencing.

Background:
Scanning this source code/the package with https://github.com/nexB/scancode-toolkit generates a `unknown-license-reference` because we cannot resolve the reference to a file that does not exist. We will also handle cases like this tentatively, but would be nice to fix it upstream too.

I can open a PR if this is something you will consider merging.

**Comment by eemeli** [comment]
Thank you, yes, a PR fixing this would be welcome!
